/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  AsyncProcessingController,
  ResponseAsyncStatus,
  TypeEnum,
} from '../src';
import { testClient } from './testClient';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper';

describe('AsyncProcessingController', () => {
  let controller : AsyncProcessingController;

  beforeAll(() => {
    controller = new AsyncProcessingController(testClient);
  });

  it('should Test Status Check', async () => {
    const statusCode = '406c66c3-21cb-47fb-80fc-843bc42507fb';

    const response = await makeApiCall(
      () => controller.statusCheck(statusCode)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: ResponseAsyncStatus = {
      type: TypeEnum.AsyncStatus,
      data: {
        code: '406c66c3-21cb-47fb-80fc-843bc42507fb',
        type: 'Transaction',
        id: '11e95f8ec39de8fbdb0a4f1a',
        progress: 100,
        ttl: BigInt(7956886942),
      },
    };
    expected.data.error = null;

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
