/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  PaymentCardReaderTokenController,
  ResponsePaymentCardReaderToken,
  Type53Enum,
} from '../src';
import { testClient } from './testClient';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper';

describe('PaymentCardReaderTokenController', () => {
  let controller : PaymentCardReaderTokenController;

  beforeAll(() => {
    controller = new PaymentCardReaderTokenController(testClient);
  });

  it('should Test Payment Card Reader Token Request', async () => {
    const productTransactionId = '11e95f8ec39de8fbdb0a4f1a';

    const response = await makeApiCall(
      () => controller.paymentCardReaderTokenRequest(productTransactionId)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: ResponsePaymentCardReaderToken = {
      type: Type53Enum.PaymentCardReaderToken,
      data: {
      },
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
