/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  AlertTypeEnum,
  AlertTypeIdEnum,
  ContactUserDefaultEntryPageEnum,
  CountryEnum,
  LocationTypeEnum,
  OrderEnum,
  ProcessMethodEnum,
  ReasonModelEnum,
  RegistrationFieldEnum,
  ReportExportTypeEnum,
  ResponseRemoveVerification,
  ResponseSendVerification,
  ResponseUser,
  ResponseUserApiKey,
  ResponseUsersCollection,
  StatusCodeEnum,
  Type123Enum,
  Type124Enum,
  Type125Enum,
  Type129Enum,
  Type130Enum,
  Type2Enum,
  Type3Enum,
  Type4Enum,
  UpdateIfExistsEnum,
  UsersController,
  UserTypeCodeEnum,
} from '../src';
import { testClient } from './testClient';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper';

describe('UsersController', () => {
  let controller : UsersController;

  beforeAll(() => {
    controller = new UsersController(testClient);
  });

  it('should Test Create a new API key', async () => {
    const userId = '11e95f8ec39de8fbdb0a4f1a';

    const response = await makeApiCall(
      () => controller.createANewAPIKey(userId, undefined)
    );

    expect(response.statusCode).toBe(201);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: ResponseUserApiKey = {
      type: Type123Enum.UserApiKey,
      data: {
        userApiKey: '234bas8dfn8238f923w2',
      },
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test List all User', async () => {
    const response = await makeApiCall(
      () => controller.listAllUser(
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: ResponseUsersCollection = {
      type: Type125Enum.UsersCollection,
      list: [
        {
          accountNumber: '5454545454545454',
          brandingDomainUrl: '{branding_domain_url}',
          cellPhone: '3339998822',
          companyName: 'Fortis Payment Systems, LLC',
          contactId: 'Sample contact ID',
          dateOfBirth: '2021-12-01',
          domainId: '11e95f8ec39de8fbdb0a4f1a',
          email: 'email@domain.com',
          emailTrxReceipt: true,
          homePhone: '3339998822',
          firstName: 'John',
          lastName: 'Smith',
          locale: 'en-US',
          officePhone: '3339998822',
          officeExtPhone: '5',
          primaryLocationId: '11e95f8ec39de8fbdb0a4f1a',
          requiresNewPassword: 'requires_new_password2',
          termsConditionCode: '20220308',
          tz: 'America/New_York',
          uiPrefs: {
            entryPage: 'dashboard',
            pageSize: 2,
            reportExportType: ReportExportTypeEnum.Csv,
            processMethod: ProcessMethodEnum.VirtualTerminal,
            defaultTerminal: '11e95f8ec39de8fbdb0a4f1a',
          },
          username: '{user_name}',
          userApiKey: '234bas8dfn8238f923w2',
          userHashKey: 'user_hash_key6',
          userTypeCode: UserTypeCodeEnum.Enum100,
          password: 'password4',
          zip: '48375',
          locationId: '11e95f8ec39de8fbdb0a4f1a',
          statusCode: StatusCodeEnum.Enum1,
          apiOnly: false,
          isInvitation: false,
          address: {
            city: 'Novi',
            state: 'MI',
            postalCode: '48375',
            country: CountryEnum.US,
          },
          id: '11e95f8ec39de8fbdb0a4f1a',
          status: true,
          loginAttempts: 0,
          lastLoginTs: 1422040992,
          createdTs: 1422040992,
          modifiedTs: 1422040992,
          createdUserId: '11e95f8ec39de8fbdb0a4f1a',
          termsAcceptedTs: 1422040992,
          termsAgreeIp: '192.168.0.10',
          currentDateTime: '2019-03-11T10:38:26-0700',
          currentLogin: 1422040992,
          logApiResponseBodyTs: 1422040992,
          locations: [
            {
              id: '11e95f8ec39de8fbdb0a4f1a',
              createdTs: 1422040992,
              modifiedTs: 1422040992,
              accountNumber: '5454545454545454',
              address: {
                city: 'Novi',
                state: 'MI',
                postalCode: '48375',
                country: CountryEnum.US,
              },
              brandingDomainId: '11e95f8ec39de8fbdb0a4f1a',
              contactEmailTrxReceiptDefault: true,
              defaultAch: '11e608a7d515f1e093242bb2',
              defaultCc: '11e608a442a5f1e092242dda',
              emailReplyTo: 'email@domain.com',
              fax: '3339998822',
              locationApiId: 'location-111111',
              locationApiKey: 'AE34BBCAADF4AE34BBCAADF4',
              locationC1: 'custom 1',
              locationC2: 'custom 2',
              locationC3: 'custom data 3',
              name: 'Sample Company Headquarters',
              officePhone: '2481234567',
              officeExtPhone: '1021021209',
              tz: 'America/New_York',
              parentId: '11e95f8ec39de8fbdb0a4f1a',
              showContactNotes: true,
              showContactFiles: true,
              createdUserId: '11e95f8ec39de8fbdb0a4f1a',
              locationType: LocationTypeEnum.Merchant,
              ticketHashKey: 'A5F443CADF4AE34BBCAADF4',
            }
          ],
          primaryLocation: {
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            accountNumber: '5454545454545454',
            address: {
              city: 'Novi',
              state: 'MI',
              postalCode: '48375',
              country: CountryEnum.US,
            },
            brandingDomainId: '11e95f8ec39de8fbdb0a4f1a',
            contactEmailTrxReceiptDefault: true,
            defaultAch: '11e608a7d515f1e093242bb2',
            defaultCc: '11e608a442a5f1e092242dda',
            emailReplyTo: 'email@domain.com',
            fax: '3339998822',
            locationApiId: 'location-111111',
            locationApiKey: 'AE34BBCAADF4AE34BBCAADF4',
            locationC1: 'custom 1',
            locationC2: 'custom 2',
            locationC3: 'custom data 3',
            name: 'Sample Company Headquarters',
            officePhone: '2481234567',
            officeExtPhone: '1021021209',
            tz: 'America/New_York',
            parentId: '11e95f8ec39de8fbdb0a4f1a',
            showContactNotes: true,
            showContactFiles: true,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            locationType: LocationTypeEnum.Merchant,
            ticketHashKey: 'A5F443CADF4AE34BBCAADF4',
          },
          receivedEmails: [
            {
              subject: 'Payment Receipt - 12skiestech',
              body: 'This email is being sent from a server.',
              sourceAddress: '"12skiestech A7t3qi" <noreply@zeamster.email>',
              returnPath: '"12skiestech A7t3qi" <noreply@zeamster.email>',
              providerId: '0100017e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000',
              domainId: '11e95f8ec39de8fbdb0a4f1a',
              reasonSent: 'Contact Email',
              reasonModel: ReasonModelEnum.Transaction,
              reasonModelId: '11e95f8ec39de8fbdb0a4f1a',
              replyTo: '"Zeamster" <emma.p@zeamster.com>',
              id: '11e95f8ec39de8fbdb0a4f1a',
              createdTs: 1422040992,
            }
          ],
          contact: {
            locationId: '11e95f8ec39de8fbdb0a4f1a',
            accountNumber: '54545433332',
            contactApiId: '137',
            firstName: 'John',
            lastName: 'Smith',
            cellPhone: '3339998822',
            balance: 245.36,
            address: {
              city: 'Novi',
              state: 'Michigan',
              postalCode: '48375',
              country: CountryEnum.US,
            },
            companyName: 'Fortis Payment Systems, LLC',
            headerMessage: 'This is a sample message for you',
            dateOfBirth: '2021-12-01',
            emailTrxReceipt: true,
            homePhone: '3339998822',
            officePhone: '3339998822',
            officePhoneExt: '5',
            headerMessageType: 0,
            updateIfExists: UpdateIfExistsEnum.Enum1,
            contactC1: 'any',
            contactC2: 'anything',
            contactC3: 'something',
            parentId: '11e95f8ec39de8fbdb0a4f1a',
            email: 'email@domain.com',
            tokenImportId: '11e95f8ec39de8fbdb0a4f1a',
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            active: true,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
          },
          isDeletable: true,
          activeNotificationAlerts: [
            {
              locationId: '11e95f8ec39de8fbdb0a4f1a',
              dateStart: '2021-12-01 10:10:00',
              dateEnd: '2021-12-01 10:10:00',
              userLocation: true,
              userContact: true,
              includeChildren: true,
              alertType: AlertTypeEnum.Enum1,
              alertTypeId: AlertTypeIdEnum.Enum1,
              id: '11e95f8ec39de8fbdb0a4f1a',
              createdTs: 1422040992,
              modifiedTs: 1422040992,
              createdUserId: '11e95f8ec39de8fbdb0a4f1a',
              modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
            }
          ],
          locationUsers: [
            {
              locationId: '11e95f8ec39de8fbdb0a4f1a',
              userId: '11e95f8ec39de8fbdb0a4f1a',
              id: '11e95f8ec39de8fbdb0a4f1a',
              createdTs: 1422040992,
              modifiedTs: 1422040992,
              createdUserId: '11e95f8ec39de8fbdb0a4f1a',
              modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
            }
          ],
          authRoles: [
            {
              userId: '11e95f8ec39de8fbdb0a4f1a',
              authRoleCode: 110,
              code: 83931,
              createdTs: 1422040992,
              modifiedTs: 1422040992,
              createdUserId: '11e95f8ec39de8fbdb0a4f1a',
              modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
            }
          ],
          changelogs: [
            {
              id: '11e95f8ec39de8fbdb0a4f1a',
              createdTs: 1422040992,
              action: 'CREATE',
              model: 'TransactionRequest',
              modelId: '11ec829598f0d4008be9aba4',
              userId: '11e95f8ec39de8fbdb0a4f1a',
              changelogDetails: [
                {
                  id: '11e95f8ec39de8fbdb0a4f1a',
                  changelogId: '11e95f8ec39de8fbdb0a4f1a',
                  field: 'next_run_ts',
                  oldValue: '1643616000',
                }
              ],
              user: {
                id: '11e95f8ec39de8fbdb0a4f1a',
                username: 'email@domain.com',
                firstName: 'Bob',
                lastName: 'Fairview',
              },
            }
          ],
          resources: {
            title: 'My terminal',
            resourceName: 'v2.addons.iframe.get',
            id: 5693,
            lastUsedDate: 1422040992,
            createdTs: 1422040992,
            modifiedTs: 1422040992,
          },
          domain: {
            url: 'fortispayrbyn9y.sandbox.zeamster.com',
            title: 'Test Brand Domain Title 2',
            logo: '',
            supportEmail: 'email@domain.com',
            allowContactSignup: true,
            allowContactRegistration: true,
            allowContactLogin: true,
            registrationFields: [
              RegistrationFieldEnum.AccountNumber
            ],
            companyName: 'company_name6',
            navColor: 'nav_color2',
            buttonPrimaryColor: 'button_primary_color0',
            logoBackgroundColor: 'logo_background_color0',
            iconBackgroundColor: 'icon_background_color4',
            menuTextBackgroundColor: 'menu_text_background_color6',
            menuTextColor: 'menu_text_color0',
            rightMenuBackgroundColor: 'right_menu_background_color8',
            rightMenuTextColor: 'right_menu_text_color8',
            buttonPrimaryTextColor: 'button_primary_text_color2',
            navLogo: 'nav_logo0',
            favIcon: 'fav_icon8',
            aesKey: 'aes_key6',
            helpText: 'help_text8',
            emailReplyTo: 'email@domain.com',
            email: 'email@domain.com',
            customJavascript: 'custom_javascript4',
            customTheme: 'custom_theme0',
            customCss: 'custom_css4',
            contactUserDefaultEntryPage: ContactUserDefaultEntryPageEnum.Dashboard,
            contactUserDefaultAuthRoles: [
              { 'key1': 'val1', 'key2': 'val2' }
            ],
            customStylesheetUrl: 'https://127.0.0.1/receiver',
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            modifiedTs: 1422040992,
          },
          createdUser: {
            accountNumber: '5454545454545454',
            brandingDomainUrl: '{branding_domain_url}',
            cellPhone: '3339998822',
            companyName: 'Fortis Payment Systems, LLC',
            contactId: '11e95f8ec39de8fbdb0a4f1a',
            dateOfBirth: '2021-12-01',
            domainId: '11e95f8ec39de8fbdb0a4f1a',
            email: 'email@domain.com',
            emailTrxReceipt: true,
            homePhone: '3339998822',
            firstName: 'John',
            lastName: 'Smith',
            locale: 'en-US',
            officePhone: '3339998822',
            officeExtPhone: '5',
            primaryLocationId: '11e95f8ec39de8fbdb0a4f1a',
            requiresNewPassword: 'requires_new_password2',
            termsConditionCode: '20220308',
            tz: 'America/New_York',
            uiPrefs: {
              entryPage: 'dashboard',
              pageSize: 2,
              reportExportType: ReportExportTypeEnum.Csv,
              processMethod: ProcessMethodEnum.VirtualTerminal,
              defaultTerminal: '11e95f8ec39de8fbdb0a4f1a',
            },
            username: '{user_name}',
            userApiKey: '234bas8dfn8238f923w2',
            userHashKey: 'user_hash_key6',
            userTypeCode: UserTypeCodeEnum.Enum100,
            password: 'password4',
            zip: '48375',
            locationId: '11e95f8ec39de8fbdb0a4f1a',
            statusCode: StatusCodeEnum.Enum1,
            apiOnly: false,
            isInvitation: false,
            address: {
              city: 'Novi',
              state: 'MI',
              postalCode: '48375',
              country: CountryEnum.US,
            },
            id: '11e95f8ec39de8fbdb0a4f1a',
            status: true,
            loginAttempts: 0,
            lastLoginTs: 1422040992,
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            termsAcceptedTs: 1422040992,
            termsAgreeIp: '192.168.0.10',
            currentDateTime: '2019-03-11T10:38:26-0700',
            currentLogin: 1422040992,
            logApiResponseBodyTs: 1422040992,
          },
          locationMarketplaces: [
            {
              locationId: '11e95f8ec39de8fbdb0a4f1a',
              marketplaceId: '11e95f8ec39de8fbdb0a4f1a',
              userId: '11e95f8ec39de8fbdb0a4f1a',
              id: '11e95f8ec39de8fbdb0a4f1a',
              createdTs: 1422040992,
              createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            }
          ],
          emailBlacklist: {
            id: '11e95f8ec39de8fbdb0a4f1a',
            isBlacklisted: true,
            detail: true,
            createdTs: 1422040992,
          },
          helppage: {
            userTypeCode: UserTypeCodeEnum.Enum100,
            body: 'Sample Body',
            title: 'Sample Title',
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
          },
        }
      ],
      links: {
        type: Type2Enum.Links,
        first: '/v1/endpoint?page[size]=10&page[number]=1',
        previous: '/v1/endpoint?page[size]=10&page[number]=5',
        next: '/v1/endpoint?page[size]=10&page[number]=7',
        last: '/v1/endpoint?page[size]=10&page[number]=42',
      },
      pagination: {
        type: Type3Enum.Pagination,
        totalCount: 423,
        pageCount: 42,
        pageNumber: 6,
        pageSize: 10,
      },
      sort: {
        type: Type4Enum.Sorting,
        fields: [
          {
            field: 'last_name',
            order: OrderEnum.Asc,
          }
        ],
      },
    };
    ((expected.list ?? [])[0].locationUsers ?? [])[0].locationApiId = null;
    (expected.list ?? [])[0].resources.priv = null;
    ((expected.list ?? [])[0].locationMarketplaces ?? [])[0].locationApiId = null;

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test Delete a user record', async () => {
    const userId = '11e95f8ec39de8fbdb0a4f1a';

    const response = await makeApiCall(
      () => controller.deleteAUserRecord(userId)
    );

    expect(response.statusCode).toBe(204);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: ResponseUser = {
      type: Type124Enum.User,
      data: {
        accountNumber: '5454545454545454',
        brandingDomainUrl: '{branding_domain_url}',
        cellPhone: '3339998822',
        companyName: 'Fortis Payment Systems, LLC',
        contactId: 'Sample contact ID',
        dateOfBirth: '2021-12-01',
        domainId: '11e95f8ec39de8fbdb0a4f1a',
        email: 'email@domain.com',
        emailTrxReceipt: true,
        homePhone: '3339998822',
        firstName: 'John',
        lastName: 'Smith',
        locale: 'en-US',
        officePhone: '3339998822',
        officeExtPhone: '5',
        primaryLocationId: '11e95f8ec39de8fbdb0a4f1a',
        requiresNewPassword: 'requires_new_password2',
        termsConditionCode: '20220308',
        tz: 'America/New_York',
        uiPrefs: {
          entryPage: 'dashboard',
          pageSize: 2,
          reportExportType: ReportExportTypeEnum.Csv,
          processMethod: ProcessMethodEnum.VirtualTerminal,
          defaultTerminal: '11e95f8ec39de8fbdb0a4f1a',
        },
        username: '{user_name}',
        userApiKey: '234bas8dfn8238f923w2',
        userHashKey: 'user_hash_key6',
        userTypeCode: UserTypeCodeEnum.Enum100,
        password: 'password4',
        zip: '48375',
        locationId: '11e95f8ec39de8fbdb0a4f1a',
        statusCode: StatusCodeEnum.Enum1,
        apiOnly: false,
        isInvitation: false,
        address: {
          city: 'Novi',
          state: 'MI',
          postalCode: '48375',
          country: CountryEnum.US,
        },
        id: '11e95f8ec39de8fbdb0a4f1a',
        status: true,
        loginAttempts: 0,
        lastLoginTs: 1422040992,
        createdTs: 1422040992,
        modifiedTs: 1422040992,
        createdUserId: '11e95f8ec39de8fbdb0a4f1a',
        termsAcceptedTs: 1422040992,
        termsAgreeIp: '192.168.0.10',
        currentDateTime: '2019-03-11T10:38:26-0700',
        currentLogin: 1422040992,
        logApiResponseBodyTs: 1422040992,
        locations: [
          {
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            accountNumber: '5454545454545454',
            address: {
              city: 'Novi',
              state: 'MI',
              postalCode: '48375',
              country: CountryEnum.US,
            },
            brandingDomainId: '11e95f8ec39de8fbdb0a4f1a',
            contactEmailTrxReceiptDefault: true,
            defaultAch: '11e608a7d515f1e093242bb2',
            defaultCc: '11e608a442a5f1e092242dda',
            emailReplyTo: 'email@domain.com',
            fax: '3339998822',
            locationApiId: 'location-111111',
            locationApiKey: 'AE34BBCAADF4AE34BBCAADF4',
            locationC1: 'custom 1',
            locationC2: 'custom 2',
            locationC3: 'custom data 3',
            name: 'Sample Company Headquarters',
            officePhone: '2481234567',
            officeExtPhone: '1021021209',
            tz: 'America/New_York',
            parentId: '11e95f8ec39de8fbdb0a4f1a',
            showContactNotes: true,
            showContactFiles: true,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            locationType: LocationTypeEnum.Merchant,
            ticketHashKey: 'A5F443CADF4AE34BBCAADF4',
          }
        ],
        primaryLocation: {
          id: '11e95f8ec39de8fbdb0a4f1a',
          createdTs: 1422040992,
          modifiedTs: 1422040992,
          accountNumber: '5454545454545454',
          address: {
            city: 'Novi',
            state: 'MI',
            postalCode: '48375',
            country: CountryEnum.US,
          },
          brandingDomainId: '11e95f8ec39de8fbdb0a4f1a',
          contactEmailTrxReceiptDefault: true,
          defaultAch: '11e608a7d515f1e093242bb2',
          defaultCc: '11e608a442a5f1e092242dda',
          emailReplyTo: 'email@domain.com',
          fax: '3339998822',
          locationApiId: 'location-111111',
          locationApiKey: 'AE34BBCAADF4AE34BBCAADF4',
          locationC1: 'custom 1',
          locationC2: 'custom 2',
          locationC3: 'custom data 3',
          name: 'Sample Company Headquarters',
          officePhone: '2481234567',
          officeExtPhone: '1021021209',
          tz: 'America/New_York',
          parentId: '11e95f8ec39de8fbdb0a4f1a',
          showContactNotes: true,
          showContactFiles: true,
          createdUserId: '11e95f8ec39de8fbdb0a4f1a',
          locationType: LocationTypeEnum.Merchant,
          ticketHashKey: 'A5F443CADF4AE34BBCAADF4',
        },
        receivedEmails: [
          {
            subject: 'Payment Receipt - 12skiestech',
            body: 'This email is being sent from a server.',
            sourceAddress: '"12skiestech A7t3qi" <noreply@zeamster.email>',
            returnPath: '"12skiestech A7t3qi" <noreply@zeamster.email>',
            providerId: '0100017e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000',
            domainId: '11e95f8ec39de8fbdb0a4f1a',
            reasonSent: 'Contact Email',
            reasonModel: ReasonModelEnum.Transaction,
            reasonModelId: '11e95f8ec39de8fbdb0a4f1a',
            replyTo: '"Zeamster" <emma.p@zeamster.com>',
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
          }
        ],
        contact: {
          locationId: '11e95f8ec39de8fbdb0a4f1a',
          accountNumber: '54545433332',
          contactApiId: '137',
          firstName: 'John',
          lastName: 'Smith',
          cellPhone: '3339998822',
          balance: 245.36,
          address: {
            city: 'Novi',
            state: 'Michigan',
            postalCode: '48375',
            country: CountryEnum.US,
          },
          companyName: 'Fortis Payment Systems, LLC',
          headerMessage: 'This is a sample message for you',
          dateOfBirth: '2021-12-01',
          emailTrxReceipt: true,
          homePhone: '3339998822',
          officePhone: '3339998822',
          officePhoneExt: '5',
          headerMessageType: 0,
          updateIfExists: UpdateIfExistsEnum.Enum1,
          contactC1: 'any',
          contactC2: 'anything',
          contactC3: 'something',
          parentId: '11e95f8ec39de8fbdb0a4f1a',
          email: 'email@domain.com',
          tokenImportId: '11e95f8ec39de8fbdb0a4f1a',
          id: '11e95f8ec39de8fbdb0a4f1a',
          createdTs: 1422040992,
          modifiedTs: 1422040992,
          active: true,
          createdUserId: '11e95f8ec39de8fbdb0a4f1a',
        },
        isDeletable: true,
        activeNotificationAlerts: [
          {
            locationId: '11e95f8ec39de8fbdb0a4f1a',
            dateStart: '2021-12-01 10:10:00',
            dateEnd: '2021-12-01 10:10:00',
            userLocation: true,
            userContact: true,
            includeChildren: true,
            alertType: AlertTypeEnum.Enum1,
            alertTypeId: AlertTypeIdEnum.Enum1,
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
          }
        ],
        locationUsers: [
          {
            locationId: '11e95f8ec39de8fbdb0a4f1a',
            userId: '11e95f8ec39de8fbdb0a4f1a',
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
          }
        ],
        authRoles: [
          {
            userId: '11e95f8ec39de8fbdb0a4f1a',
            authRoleCode: 110,
            code: 83931,
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
          }
        ],
        changelogs: [
          {
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            action: 'CREATE',
            model: 'TransactionRequest',
            modelId: '11ec829598f0d4008be9aba4',
            userId: '11e95f8ec39de8fbdb0a4f1a',
            changelogDetails: [
              {
                id: '11e95f8ec39de8fbdb0a4f1a',
                changelogId: '11e95f8ec39de8fbdb0a4f1a',
                field: 'next_run_ts',
                oldValue: '1643616000',
              }
            ],
            user: {
              id: '11e95f8ec39de8fbdb0a4f1a',
              username: 'email@domain.com',
              firstName: 'Bob',
              lastName: 'Fairview',
            },
          }
        ],
        resources: {
          title: 'My terminal',
          resourceName: 'v2.addons.iframe.get',
          id: 5693,
          lastUsedDate: 1422040992,
          createdTs: 1422040992,
          modifiedTs: 1422040992,
        },
        domain: {
          url: 'fortispayrbyn9y.sandbox.zeamster.com',
          title: 'Test Brand Domain Title 2',
          logo: '',
          supportEmail: 'email@domain.com',
          allowContactSignup: true,
          allowContactRegistration: true,
          allowContactLogin: true,
          registrationFields: [
            RegistrationFieldEnum.AccountNumber
          ],
          companyName: 'company_name6',
          navColor: 'nav_color2',
          buttonPrimaryColor: 'button_primary_color0',
          logoBackgroundColor: 'logo_background_color0',
          iconBackgroundColor: 'icon_background_color4',
          menuTextBackgroundColor: 'menu_text_background_color6',
          menuTextColor: 'menu_text_color0',
          rightMenuBackgroundColor: 'right_menu_background_color8',
          rightMenuTextColor: 'right_menu_text_color8',
          buttonPrimaryTextColor: 'button_primary_text_color2',
          navLogo: 'nav_logo0',
          favIcon: 'fav_icon8',
          aesKey: 'aes_key6',
          helpText: 'help_text8',
          emailReplyTo: 'email@domain.com',
          email: 'email@domain.com',
          customJavascript: 'custom_javascript4',
          customTheme: 'custom_theme0',
          customCss: 'custom_css4',
          contactUserDefaultEntryPage: ContactUserDefaultEntryPageEnum.Dashboard,
          contactUserDefaultAuthRoles: [
            { 'key1': 'val1', 'key2': 'val2' }
          ],
          customStylesheetUrl: 'https://127.0.0.1/receiver',
          id: '11e95f8ec39de8fbdb0a4f1a',
          createdTs: 1422040992,
          modifiedTs: 1422040992,
        },
        createdUser: {
          accountNumber: '5454545454545454',
          brandingDomainUrl: '{branding_domain_url}',
          cellPhone: '3339998822',
          companyName: 'Fortis Payment Systems, LLC',
          contactId: '11e95f8ec39de8fbdb0a4f1a',
          dateOfBirth: '2021-12-01',
          domainId: '11e95f8ec39de8fbdb0a4f1a',
          email: 'email@domain.com',
          emailTrxReceipt: true,
          homePhone: '3339998822',
          firstName: 'John',
          lastName: 'Smith',
          locale: 'en-US',
          officePhone: '3339998822',
          officeExtPhone: '5',
          primaryLocationId: '11e95f8ec39de8fbdb0a4f1a',
          requiresNewPassword: 'requires_new_password2',
          termsConditionCode: '20220308',
          tz: 'America/New_York',
          uiPrefs: {
            entryPage: 'dashboard',
            pageSize: 2,
            reportExportType: ReportExportTypeEnum.Csv,
            processMethod: ProcessMethodEnum.VirtualTerminal,
            defaultTerminal: '11e95f8ec39de8fbdb0a4f1a',
          },
          username: '{user_name}',
          userApiKey: '234bas8dfn8238f923w2',
          userHashKey: 'user_hash_key6',
          userTypeCode: UserTypeCodeEnum.Enum100,
          password: 'password4',
          zip: '48375',
          locationId: '11e95f8ec39de8fbdb0a4f1a',
          statusCode: StatusCodeEnum.Enum1,
          apiOnly: false,
          isInvitation: false,
          address: {
            city: 'Novi',
            state: 'MI',
            postalCode: '48375',
            country: CountryEnum.US,
          },
          id: '11e95f8ec39de8fbdb0a4f1a',
          status: true,
          loginAttempts: 0,
          lastLoginTs: 1422040992,
          createdTs: 1422040992,
          modifiedTs: 1422040992,
          createdUserId: '11e95f8ec39de8fbdb0a4f1a',
          termsAcceptedTs: 1422040992,
          termsAgreeIp: '192.168.0.10',
          currentDateTime: '2019-03-11T10:38:26-0700',
          currentLogin: 1422040992,
          logApiResponseBodyTs: 1422040992,
        },
        locationMarketplaces: [
          {
            locationId: '11e95f8ec39de8fbdb0a4f1a',
            marketplaceId: '11e95f8ec39de8fbdb0a4f1a',
            userId: '11e95f8ec39de8fbdb0a4f1a',
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
          }
        ],
        emailBlacklist: {
          id: '11e95f8ec39de8fbdb0a4f1a',
          isBlacklisted: true,
          detail: true,
          createdTs: 1422040992,
        },
        helppage: {
          userTypeCode: UserTypeCodeEnum.Enum100,
          body: 'Sample Body',
          title: 'Sample Title',
          id: '11e95f8ec39de8fbdb0a4f1a',
          createdTs: 1422040992,
          modifiedTs: 1422040992,
          createdUserId: '11e95f8ec39de8fbdb0a4f1a',
          modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
        },
      },
    };
    (expected.data.locationUsers ?? [])[0].locationApiId = null;
    expected.data.resources.priv = null;
    (expected.data.locationMarketplaces ?? [])[0].locationApiId = null;

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test View single user record', async () => {
    const userId = '11e95f8ec39de8fbdb0a4f1a';

    const response = await makeApiCall(
      () => controller.viewSingleUserRecord(userId, undefined, undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: ResponseUser = {
      type: Type124Enum.User,
      data: {
        accountNumber: '5454545454545454',
        brandingDomainUrl: '{branding_domain_url}',
        cellPhone: '3339998822',
        companyName: 'Fortis Payment Systems, LLC',
        contactId: 'Sample contact ID',
        dateOfBirth: '2021-12-01',
        domainId: '11e95f8ec39de8fbdb0a4f1a',
        email: 'email@domain.com',
        emailTrxReceipt: true,
        homePhone: '3339998822',
        firstName: 'John',
        lastName: 'Smith',
        locale: 'en-US',
        officePhone: '3339998822',
        officeExtPhone: '5',
        primaryLocationId: '11e95f8ec39de8fbdb0a4f1a',
        requiresNewPassword: 'requires_new_password2',
        termsConditionCode: '20220308',
        tz: 'America/New_York',
        uiPrefs: {
          entryPage: 'dashboard',
          pageSize: 2,
          reportExportType: ReportExportTypeEnum.Csv,
          processMethod: ProcessMethodEnum.VirtualTerminal,
          defaultTerminal: '11e95f8ec39de8fbdb0a4f1a',
        },
        username: '{user_name}',
        userApiKey: '234bas8dfn8238f923w2',
        userHashKey: 'user_hash_key6',
        userTypeCode: UserTypeCodeEnum.Enum100,
        password: 'password4',
        zip: '48375',
        locationId: '11e95f8ec39de8fbdb0a4f1a',
        statusCode: StatusCodeEnum.Enum1,
        apiOnly: false,
        isInvitation: false,
        address: {
          city: 'Novi',
          state: 'MI',
          postalCode: '48375',
          country: CountryEnum.US,
        },
        id: '11e95f8ec39de8fbdb0a4f1a',
        status: true,
        loginAttempts: 0,
        lastLoginTs: 1422040992,
        createdTs: 1422040992,
        modifiedTs: 1422040992,
        createdUserId: '11e95f8ec39de8fbdb0a4f1a',
        termsAcceptedTs: 1422040992,
        termsAgreeIp: '192.168.0.10',
        currentDateTime: '2019-03-11T10:38:26-0700',
        currentLogin: 1422040992,
        logApiResponseBodyTs: 1422040992,
        locations: [
          {
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            accountNumber: '5454545454545454',
            address: {
              city: 'Novi',
              state: 'MI',
              postalCode: '48375',
              country: CountryEnum.US,
            },
            brandingDomainId: '11e95f8ec39de8fbdb0a4f1a',
            contactEmailTrxReceiptDefault: true,
            defaultAch: '11e608a7d515f1e093242bb2',
            defaultCc: '11e608a442a5f1e092242dda',
            emailReplyTo: 'email@domain.com',
            fax: '3339998822',
            locationApiId: 'location-111111',
            locationApiKey: 'AE34BBCAADF4AE34BBCAADF4',
            locationC1: 'custom 1',
            locationC2: 'custom 2',
            locationC3: 'custom data 3',
            name: 'Sample Company Headquarters',
            officePhone: '2481234567',
            officeExtPhone: '1021021209',
            tz: 'America/New_York',
            parentId: '11e95f8ec39de8fbdb0a4f1a',
            showContactNotes: true,
            showContactFiles: true,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            locationType: LocationTypeEnum.Merchant,
            ticketHashKey: 'A5F443CADF4AE34BBCAADF4',
          }
        ],
        primaryLocation: {
          id: '11e95f8ec39de8fbdb0a4f1a',
          createdTs: 1422040992,
          modifiedTs: 1422040992,
          accountNumber: '5454545454545454',
          address: {
            city: 'Novi',
            state: 'MI',
            postalCode: '48375',
            country: CountryEnum.US,
          },
          brandingDomainId: '11e95f8ec39de8fbdb0a4f1a',
          contactEmailTrxReceiptDefault: true,
          defaultAch: '11e608a7d515f1e093242bb2',
          defaultCc: '11e608a442a5f1e092242dda',
          emailReplyTo: 'email@domain.com',
          fax: '3339998822',
          locationApiId: 'location-111111',
          locationApiKey: 'AE34BBCAADF4AE34BBCAADF4',
          locationC1: 'custom 1',
          locationC2: 'custom 2',
          locationC3: 'custom data 3',
          name: 'Sample Company Headquarters',
          officePhone: '2481234567',
          officeExtPhone: '1021021209',
          tz: 'America/New_York',
          parentId: '11e95f8ec39de8fbdb0a4f1a',
          showContactNotes: true,
          showContactFiles: true,
          createdUserId: '11e95f8ec39de8fbdb0a4f1a',
          locationType: LocationTypeEnum.Merchant,
          ticketHashKey: 'A5F443CADF4AE34BBCAADF4',
        },
        receivedEmails: [
          {
            subject: 'Payment Receipt - 12skiestech',
            body: 'This email is being sent from a server.',
            sourceAddress: '"12skiestech A7t3qi" <noreply@zeamster.email>',
            returnPath: '"12skiestech A7t3qi" <noreply@zeamster.email>',
            providerId: '0100017e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000',
            domainId: '11e95f8ec39de8fbdb0a4f1a',
            reasonSent: 'Contact Email',
            reasonModel: ReasonModelEnum.Transaction,
            reasonModelId: '11e95f8ec39de8fbdb0a4f1a',
            replyTo: '"Zeamster" <emma.p@zeamster.com>',
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
          }
        ],
        contact: {
          locationId: '11e95f8ec39de8fbdb0a4f1a',
          accountNumber: '54545433332',
          contactApiId: '137',
          firstName: 'John',
          lastName: 'Smith',
          cellPhone: '3339998822',
          balance: 245.36,
          address: {
            city: 'Novi',
            state: 'Michigan',
            postalCode: '48375',
            country: CountryEnum.US,
          },
          companyName: 'Fortis Payment Systems, LLC',
          headerMessage: 'This is a sample message for you',
          dateOfBirth: '2021-12-01',
          emailTrxReceipt: true,
          homePhone: '3339998822',
          officePhone: '3339998822',
          officePhoneExt: '5',
          headerMessageType: 0,
          updateIfExists: UpdateIfExistsEnum.Enum1,
          contactC1: 'any',
          contactC2: 'anything',
          contactC3: 'something',
          parentId: '11e95f8ec39de8fbdb0a4f1a',
          email: 'email@domain.com',
          tokenImportId: '11e95f8ec39de8fbdb0a4f1a',
          id: '11e95f8ec39de8fbdb0a4f1a',
          createdTs: 1422040992,
          modifiedTs: 1422040992,
          active: true,
          createdUserId: '11e95f8ec39de8fbdb0a4f1a',
        },
        isDeletable: true,
        activeNotificationAlerts: [
          {
            locationId: '11e95f8ec39de8fbdb0a4f1a',
            dateStart: '2021-12-01 10:10:00',
            dateEnd: '2021-12-01 10:10:00',
            userLocation: true,
            userContact: true,
            includeChildren: true,
            alertType: AlertTypeEnum.Enum1,
            alertTypeId: AlertTypeIdEnum.Enum1,
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
          }
        ],
        locationUsers: [
          {
            locationId: '11e95f8ec39de8fbdb0a4f1a',
            userId: '11e95f8ec39de8fbdb0a4f1a',
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
          }
        ],
        authRoles: [
          {
            userId: '11e95f8ec39de8fbdb0a4f1a',
            authRoleCode: 110,
            code: 83931,
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
          }
        ],
        changelogs: [
          {
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            action: 'CREATE',
            model: 'TransactionRequest',
            modelId: '11ec829598f0d4008be9aba4',
            userId: '11e95f8ec39de8fbdb0a4f1a',
            changelogDetails: [
              {
                id: '11e95f8ec39de8fbdb0a4f1a',
                changelogId: '11e95f8ec39de8fbdb0a4f1a',
                field: 'next_run_ts',
                oldValue: '1643616000',
              }
            ],
            user: {
              id: '11e95f8ec39de8fbdb0a4f1a',
              username: 'email@domain.com',
              firstName: 'Bob',
              lastName: 'Fairview',
            },
          }
        ],
        resources: {
          title: 'My terminal',
          resourceName: 'v2.addons.iframe.get',
          id: 5693,
          lastUsedDate: 1422040992,
          createdTs: 1422040992,
          modifiedTs: 1422040992,
        },
        domain: {
          url: 'fortispayrbyn9y.sandbox.zeamster.com',
          title: 'Test Brand Domain Title 2',
          logo: '',
          supportEmail: 'email@domain.com',
          allowContactSignup: true,
          allowContactRegistration: true,
          allowContactLogin: true,
          registrationFields: [
            RegistrationFieldEnum.AccountNumber
          ],
          companyName: 'company_name6',
          navColor: 'nav_color2',
          buttonPrimaryColor: 'button_primary_color0',
          logoBackgroundColor: 'logo_background_color0',
          iconBackgroundColor: 'icon_background_color4',
          menuTextBackgroundColor: 'menu_text_background_color6',
          menuTextColor: 'menu_text_color0',
          rightMenuBackgroundColor: 'right_menu_background_color8',
          rightMenuTextColor: 'right_menu_text_color8',
          buttonPrimaryTextColor: 'button_primary_text_color2',
          navLogo: 'nav_logo0',
          favIcon: 'fav_icon8',
          aesKey: 'aes_key6',
          helpText: 'help_text8',
          emailReplyTo: 'email@domain.com',
          email: 'email@domain.com',
          customJavascript: 'custom_javascript4',
          customTheme: 'custom_theme0',
          customCss: 'custom_css4',
          contactUserDefaultEntryPage: ContactUserDefaultEntryPageEnum.Dashboard,
          contactUserDefaultAuthRoles: [
            { 'key1': 'val1', 'key2': 'val2' }
          ],
          customStylesheetUrl: 'https://127.0.0.1/receiver',
          id: '11e95f8ec39de8fbdb0a4f1a',
          createdTs: 1422040992,
          modifiedTs: 1422040992,
        },
        createdUser: {
          accountNumber: '5454545454545454',
          brandingDomainUrl: '{branding_domain_url}',
          cellPhone: '3339998822',
          companyName: 'Fortis Payment Systems, LLC',
          contactId: '11e95f8ec39de8fbdb0a4f1a',
          dateOfBirth: '2021-12-01',
          domainId: '11e95f8ec39de8fbdb0a4f1a',
          email: 'email@domain.com',
          emailTrxReceipt: true,
          homePhone: '3339998822',
          firstName: 'John',
          lastName: 'Smith',
          locale: 'en-US',
          officePhone: '3339998822',
          officeExtPhone: '5',
          primaryLocationId: '11e95f8ec39de8fbdb0a4f1a',
          requiresNewPassword: 'requires_new_password2',
          termsConditionCode: '20220308',
          tz: 'America/New_York',
          uiPrefs: {
            entryPage: 'dashboard',
            pageSize: 2,
            reportExportType: ReportExportTypeEnum.Csv,
            processMethod: ProcessMethodEnum.VirtualTerminal,
            defaultTerminal: '11e95f8ec39de8fbdb0a4f1a',
          },
          username: '{user_name}',
          userApiKey: '234bas8dfn8238f923w2',
          userHashKey: 'user_hash_key6',
          userTypeCode: UserTypeCodeEnum.Enum100,
          password: 'password4',
          zip: '48375',
          locationId: '11e95f8ec39de8fbdb0a4f1a',
          statusCode: StatusCodeEnum.Enum1,
          apiOnly: false,
          isInvitation: false,
          address: {
            city: 'Novi',
            state: 'MI',
            postalCode: '48375',
            country: CountryEnum.US,
          },
          id: '11e95f8ec39de8fbdb0a4f1a',
          status: true,
          loginAttempts: 0,
          lastLoginTs: 1422040992,
          createdTs: 1422040992,
          modifiedTs: 1422040992,
          createdUserId: '11e95f8ec39de8fbdb0a4f1a',
          termsAcceptedTs: 1422040992,
          termsAgreeIp: '192.168.0.10',
          currentDateTime: '2019-03-11T10:38:26-0700',
          currentLogin: 1422040992,
          logApiResponseBodyTs: 1422040992,
        },
        locationMarketplaces: [
          {
            locationId: '11e95f8ec39de8fbdb0a4f1a',
            marketplaceId: '11e95f8ec39de8fbdb0a4f1a',
            userId: '11e95f8ec39de8fbdb0a4f1a',
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
          }
        ],
        emailBlacklist: {
          id: '11e95f8ec39de8fbdb0a4f1a',
          isBlacklisted: true,
          detail: true,
          createdTs: 1422040992,
        },
        helppage: {
          userTypeCode: UserTypeCodeEnum.Enum100,
          body: 'Sample Body',
          title: 'Sample Title',
          id: '11e95f8ec39de8fbdb0a4f1a',
          createdTs: 1422040992,
          modifiedTs: 1422040992,
          createdUserId: '11e95f8ec39de8fbdb0a4f1a',
          modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
        },
      },
    };
    (expected.data.locationUsers ?? [])[0].locationApiId = null;
    expected.data.resources.priv = null;
    (expected.data.locationMarketplaces ?? [])[0].locationApiId = null;

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test View self record', async () => {
    const response = await makeApiCall(
      () => controller.viewSelfRecord(undefined, undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: ResponseUser = {
      type: Type124Enum.User,
      data: {
        accountNumber: '5454545454545454',
        brandingDomainUrl: '{branding_domain_url}',
        cellPhone: '3339998822',
        companyName: 'Fortis Payment Systems, LLC',
        contactId: 'Sample contact ID',
        dateOfBirth: '2021-12-01',
        domainId: '11e95f8ec39de8fbdb0a4f1a',
        email: 'email@domain.com',
        emailTrxReceipt: true,
        homePhone: '3339998822',
        firstName: 'John',
        lastName: 'Smith',
        locale: 'en-US',
        officePhone: '3339998822',
        officeExtPhone: '5',
        primaryLocationId: '11e95f8ec39de8fbdb0a4f1a',
        requiresNewPassword: 'requires_new_password2',
        termsConditionCode: '20220308',
        tz: 'America/New_York',
        uiPrefs: {
          entryPage: 'dashboard',
          pageSize: 2,
          reportExportType: ReportExportTypeEnum.Csv,
          processMethod: ProcessMethodEnum.VirtualTerminal,
          defaultTerminal: '11e95f8ec39de8fbdb0a4f1a',
        },
        username: '{user_name}',
        userApiKey: '234bas8dfn8238f923w2',
        userHashKey: 'user_hash_key6',
        userTypeCode: UserTypeCodeEnum.Enum100,
        password: 'password4',
        zip: '48375',
        locationId: '11e95f8ec39de8fbdb0a4f1a',
        statusCode: StatusCodeEnum.Enum1,
        apiOnly: false,
        isInvitation: false,
        address: {
          city: 'Novi',
          state: 'MI',
          postalCode: '48375',
          country: CountryEnum.US,
        },
        id: '11e95f8ec39de8fbdb0a4f1a',
        status: true,
        loginAttempts: 0,
        lastLoginTs: 1422040992,
        createdTs: 1422040992,
        modifiedTs: 1422040992,
        createdUserId: '11e95f8ec39de8fbdb0a4f1a',
        termsAcceptedTs: 1422040992,
        termsAgreeIp: '192.168.0.10',
        currentDateTime: '2019-03-11T10:38:26-0700',
        currentLogin: 1422040992,
        logApiResponseBodyTs: 1422040992,
        locations: [
          {
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            accountNumber: '5454545454545454',
            address: {
              city: 'Novi',
              state: 'MI',
              postalCode: '48375',
              country: CountryEnum.US,
            },
            brandingDomainId: '11e95f8ec39de8fbdb0a4f1a',
            contactEmailTrxReceiptDefault: true,
            defaultAch: '11e608a7d515f1e093242bb2',
            defaultCc: '11e608a442a5f1e092242dda',
            emailReplyTo: 'email@domain.com',
            fax: '3339998822',
            locationApiId: 'location-111111',
            locationApiKey: 'AE34BBCAADF4AE34BBCAADF4',
            locationC1: 'custom 1',
            locationC2: 'custom 2',
            locationC3: 'custom data 3',
            name: 'Sample Company Headquarters',
            officePhone: '2481234567',
            officeExtPhone: '1021021209',
            tz: 'America/New_York',
            parentId: '11e95f8ec39de8fbdb0a4f1a',
            showContactNotes: true,
            showContactFiles: true,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            locationType: LocationTypeEnum.Merchant,
            ticketHashKey: 'A5F443CADF4AE34BBCAADF4',
          }
        ],
        primaryLocation: {
          id: '11e95f8ec39de8fbdb0a4f1a',
          createdTs: 1422040992,
          modifiedTs: 1422040992,
          accountNumber: '5454545454545454',
          address: {
            city: 'Novi',
            state: 'MI',
            postalCode: '48375',
            country: CountryEnum.US,
          },
          brandingDomainId: '11e95f8ec39de8fbdb0a4f1a',
          contactEmailTrxReceiptDefault: true,
          defaultAch: '11e608a7d515f1e093242bb2',
          defaultCc: '11e608a442a5f1e092242dda',
          emailReplyTo: 'email@domain.com',
          fax: '3339998822',
          locationApiId: 'location-111111',
          locationApiKey: 'AE34BBCAADF4AE34BBCAADF4',
          locationC1: 'custom 1',
          locationC2: 'custom 2',
          locationC3: 'custom data 3',
          name: 'Sample Company Headquarters',
          officePhone: '2481234567',
          officeExtPhone: '1021021209',
          tz: 'America/New_York',
          parentId: '11e95f8ec39de8fbdb0a4f1a',
          showContactNotes: true,
          showContactFiles: true,
          createdUserId: '11e95f8ec39de8fbdb0a4f1a',
          locationType: LocationTypeEnum.Merchant,
          ticketHashKey: 'A5F443CADF4AE34BBCAADF4',
        },
        receivedEmails: [
          {
            subject: 'Payment Receipt - 12skiestech',
            body: 'This email is being sent from a server.',
            sourceAddress: '"12skiestech A7t3qi" <noreply@zeamster.email>',
            returnPath: '"12skiestech A7t3qi" <noreply@zeamster.email>',
            providerId: '0100017e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000',
            domainId: '11e95f8ec39de8fbdb0a4f1a',
            reasonSent: 'Contact Email',
            reasonModel: ReasonModelEnum.Transaction,
            reasonModelId: '11e95f8ec39de8fbdb0a4f1a',
            replyTo: '"Zeamster" <emma.p@zeamster.com>',
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
          }
        ],
        contact: {
          locationId: '11e95f8ec39de8fbdb0a4f1a',
          accountNumber: '54545433332',
          contactApiId: '137',
          firstName: 'John',
          lastName: 'Smith',
          cellPhone: '3339998822',
          balance: 245.36,
          address: {
            city: 'Novi',
            state: 'Michigan',
            postalCode: '48375',
            country: CountryEnum.US,
          },
          companyName: 'Fortis Payment Systems, LLC',
          headerMessage: 'This is a sample message for you',
          dateOfBirth: '2021-12-01',
          emailTrxReceipt: true,
          homePhone: '3339998822',
          officePhone: '3339998822',
          officePhoneExt: '5',
          headerMessageType: 0,
          updateIfExists: UpdateIfExistsEnum.Enum1,
          contactC1: 'any',
          contactC2: 'anything',
          contactC3: 'something',
          parentId: '11e95f8ec39de8fbdb0a4f1a',
          email: 'email@domain.com',
          tokenImportId: '11e95f8ec39de8fbdb0a4f1a',
          id: '11e95f8ec39de8fbdb0a4f1a',
          createdTs: 1422040992,
          modifiedTs: 1422040992,
          active: true,
          createdUserId: '11e95f8ec39de8fbdb0a4f1a',
        },
        isDeletable: true,
        activeNotificationAlerts: [
          {
            locationId: '11e95f8ec39de8fbdb0a4f1a',
            dateStart: '2021-12-01 10:10:00',
            dateEnd: '2021-12-01 10:10:00',
            userLocation: true,
            userContact: true,
            includeChildren: true,
            alertType: AlertTypeEnum.Enum1,
            alertTypeId: AlertTypeIdEnum.Enum1,
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
          }
        ],
        locationUsers: [
          {
            locationId: '11e95f8ec39de8fbdb0a4f1a',
            userId: '11e95f8ec39de8fbdb0a4f1a',
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
          }
        ],
        authRoles: [
          {
            userId: '11e95f8ec39de8fbdb0a4f1a',
            authRoleCode: 110,
            code: 83931,
            createdTs: 1422040992,
            modifiedTs: 1422040992,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
            modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
          }
        ],
        changelogs: [
          {
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            action: 'CREATE',
            model: 'TransactionRequest',
            modelId: '11ec829598f0d4008be9aba4',
            userId: '11e95f8ec39de8fbdb0a4f1a',
            changelogDetails: [
              {
                id: '11e95f8ec39de8fbdb0a4f1a',
                changelogId: '11e95f8ec39de8fbdb0a4f1a',
                field: 'next_run_ts',
                oldValue: '1643616000',
              }
            ],
            user: {
              id: '11e95f8ec39de8fbdb0a4f1a',
              username: 'email@domain.com',
              firstName: 'Bob',
              lastName: 'Fairview',
            },
          }
        ],
        resources: {
          title: 'My terminal',
          resourceName: 'v2.addons.iframe.get',
          id: 5693,
          lastUsedDate: 1422040992,
          createdTs: 1422040992,
          modifiedTs: 1422040992,
        },
        domain: {
          url: 'fortispayrbyn9y.sandbox.zeamster.com',
          title: 'Test Brand Domain Title 2',
          logo: '',
          supportEmail: 'email@domain.com',
          allowContactSignup: true,
          allowContactRegistration: true,
          allowContactLogin: true,
          registrationFields: [
            RegistrationFieldEnum.AccountNumber
          ],
          companyName: 'company_name6',
          navColor: 'nav_color2',
          buttonPrimaryColor: 'button_primary_color0',
          logoBackgroundColor: 'logo_background_color0',
          iconBackgroundColor: 'icon_background_color4',
          menuTextBackgroundColor: 'menu_text_background_color6',
          menuTextColor: 'menu_text_color0',
          rightMenuBackgroundColor: 'right_menu_background_color8',
          rightMenuTextColor: 'right_menu_text_color8',
          buttonPrimaryTextColor: 'button_primary_text_color2',
          navLogo: 'nav_logo0',
          favIcon: 'fav_icon8',
          aesKey: 'aes_key6',
          helpText: 'help_text8',
          emailReplyTo: 'email@domain.com',
          email: 'email@domain.com',
          customJavascript: 'custom_javascript4',
          customTheme: 'custom_theme0',
          customCss: 'custom_css4',
          contactUserDefaultEntryPage: ContactUserDefaultEntryPageEnum.Dashboard,
          contactUserDefaultAuthRoles: [
            { 'key1': 'val1', 'key2': 'val2' }
          ],
          customStylesheetUrl: 'https://127.0.0.1/receiver',
          id: '11e95f8ec39de8fbdb0a4f1a',
          createdTs: 1422040992,
          modifiedTs: 1422040992,
        },
        createdUser: {
          accountNumber: '5454545454545454',
          brandingDomainUrl: '{branding_domain_url}',
          cellPhone: '3339998822',
          companyName: 'Fortis Payment Systems, LLC',
          contactId: '11e95f8ec39de8fbdb0a4f1a',
          dateOfBirth: '2021-12-01',
          domainId: '11e95f8ec39de8fbdb0a4f1a',
          email: 'email@domain.com',
          emailTrxReceipt: true,
          homePhone: '3339998822',
          firstName: 'John',
          lastName: 'Smith',
          locale: 'en-US',
          officePhone: '3339998822',
          officeExtPhone: '5',
          primaryLocationId: '11e95f8ec39de8fbdb0a4f1a',
          requiresNewPassword: 'requires_new_password2',
          termsConditionCode: '20220308',
          tz: 'America/New_York',
          uiPrefs: {
            entryPage: 'dashboard',
            pageSize: 2,
            reportExportType: ReportExportTypeEnum.Csv,
            processMethod: ProcessMethodEnum.VirtualTerminal,
            defaultTerminal: '11e95f8ec39de8fbdb0a4f1a',
          },
          username: '{user_name}',
          userApiKey: '234bas8dfn8238f923w2',
          userHashKey: 'user_hash_key6',
          userTypeCode: UserTypeCodeEnum.Enum100,
          password: 'password4',
          zip: '48375',
          locationId: '11e95f8ec39de8fbdb0a4f1a',
          statusCode: StatusCodeEnum.Enum1,
          apiOnly: false,
          isInvitation: false,
          address: {
            city: 'Novi',
            state: 'MI',
            postalCode: '48375',
            country: CountryEnum.US,
          },
          id: '11e95f8ec39de8fbdb0a4f1a',
          status: true,
          loginAttempts: 0,
          lastLoginTs: 1422040992,
          createdTs: 1422040992,
          modifiedTs: 1422040992,
          createdUserId: '11e95f8ec39de8fbdb0a4f1a',
          termsAcceptedTs: 1422040992,
          termsAgreeIp: '192.168.0.10',
          currentDateTime: '2019-03-11T10:38:26-0700',
          currentLogin: 1422040992,
          logApiResponseBodyTs: 1422040992,
        },
        locationMarketplaces: [
          {
            locationId: '11e95f8ec39de8fbdb0a4f1a',
            marketplaceId: '11e95f8ec39de8fbdb0a4f1a',
            userId: '11e95f8ec39de8fbdb0a4f1a',
            id: '11e95f8ec39de8fbdb0a4f1a',
            createdTs: 1422040992,
            createdUserId: '11e95f8ec39de8fbdb0a4f1a',
          }
        ],
        emailBlacklist: {
          id: '11e95f8ec39de8fbdb0a4f1a',
          isBlacklisted: true,
          detail: true,
          createdTs: 1422040992,
        },
        helppage: {
          userTypeCode: UserTypeCodeEnum.Enum100,
          body: 'Sample Body',
          title: 'Sample Title',
          id: '11e95f8ec39de8fbdb0a4f1a',
          createdTs: 1422040992,
          modifiedTs: 1422040992,
          createdUserId: '11e95f8ec39de8fbdb0a4f1a',
          modifiedUserId: '11e95f8ec39de8fbdb0a4f1a',
        },
      },
    };
    (expected.data.locationUsers ?? [])[0].locationApiId = null;
    expected.data.resources.priv = null;
    (expected.data.locationMarketplaces ?? [])[0].locationApiId = null;

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test Remove verification', async () => {
    const userId = '';

    const response = await makeApiCall(
      () => controller.removeVerification(userId)
    );

    expect(response.statusCode).toBe(204);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: ResponseRemoveVerification = {
      type: Type129Enum.RemoveVerification,
      data: {
        id: '11e95f8ec39de8fbdb0a4f1a',
        userId: '11e95f8ec39de8fbdb0a4f1a',
        hash: '123456781234567812345678',
        createdTs: 1422040992,
      },
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test Send verification', async () => {
    const userId = '';

    const response = await makeApiCall(
      () => controller.sendVerification(userId)
    );

    expect(response.statusCode).toBe(201);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: ResponseSendVerification = {
      type: Type130Enum.SendVerification,
      data: {
        id: '11e95f8ec39de8fbdb0a4f1a',
        userId: '11e95f8ec39de8fbdb0a4f1a',
        hash: '123456781234567812345678',
        createdTs: 1422040992,
      },
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
