/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Detail1 } from '../models/detail1';

/**
 * Creates an instance of Response
 */
interface Response {
  /** Message type */
  type?: string;
  /** Unique identifier for this API call */
  id?: string;
  /** HTTP status code */
  statusCode?: number;
  /** Error title */
  title?: string;
  /** Error details */
  detail?: Detail1;
  /** Object with additional error details */
  meta?: unknown;
  [key: string]: unknown;
}

export class ResponseError extends ApiError<Response> {}
