/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, number, Schema } from '../../schema';

/** This is a container type for any-of types. */
export type FilterByValueCase0 = number;

export const filterByValueCase0Schema: Schema<FilterByValueCase0> = anyOf([
  number(),
]);

export namespace FilterByValueCase0 {
  /**
   * Validation method to narrow down union type to number type case.
   *
   * This is Precision case.
   */
  export function isNumber(value: unknown): value is number {
    return typeof value === 'number';
  }
}
