/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, string } from '../../schema';

/** This is a container type for any-of types. */
export type List14LocationId = string;

export const list14LocationIdSchema: Schema<List14LocationId> = anyOf([
  string(),
]);

export namespace List14LocationId {
  /**
   * Validation method to narrow down union type to string type case.
   *
   * This is String case.
   */
  export function isString(value: unknown): value is string {
    return typeof value === 'string';
  }
}
