/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, boolean, Schema } from '../../schema';

/** This is a container type for any-of types. */
export type V1ElementsTransactionIntentionRequestAllowPartialAuthorizationOverride =
  | boolean;

export const v1ElementsTransactionIntentionRequestAllowPartialAuthorizationOverrideSchema: Schema<V1ElementsTransactionIntentionRequestAllowPartialAuthorizationOverride> = anyOf(
  [boolean()]
);

export namespace V1ElementsTransactionIntentionRequestAllowPartialAuthorizationOverride {
  /**
   * Validation method to narrow down union type to boolean type case.
   *
   * This is Boolean case.
   */
  export function isBoolean(value: unknown): value is boolean {
    return typeof value === 'boolean';
  }
}
