/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  ResponseAsyncStatus,
  responseAsyncStatusSchema,
} from '../models/responseAsyncStatus';
import { string } from '../schema';
import { BaseController } from './baseController';
import { Response401tokenError } from '../errors/response401tokenError';

export class AsyncProcessingController extends BaseController {
  /**
   * Retrieve the current status for a particular code.
   *
   * @param statusCode  A [UUID v4](https://datatracker.ietf.org/doc/html/rfc4122) that's unique for the
   *                              Async Request
   * @return Response from the API call
   */
  async statusCheck(
    statusCode: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ResponseAsyncStatus>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ statusCode: [statusCode, string()] });
    req.appendTemplatePath`/v1/async/status/${mapped.statusCode}`;
    req.throwOn(401, Response401tokenError, 'Unauthorized');
    req.authenticate([{ userId: true, userApiKey: true, developerId: true }]);
    return req.callAsJson(responseAsyncStatusSchema, requestOptions);
  }
}
