/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  ResponseMerchantDetails,
  responseMerchantDetailsSchema,
} from '../models/responseMerchantDetails';
import {
  V1WalletProviderMerchantDetailsRequest,
  v1WalletProviderMerchantDetailsRequestSchema,
} from '../models/v1WalletProviderMerchantDetailsRequest';
import { BaseController } from './baseController';
import { Response401tokenError } from '../errors/response401tokenError';
import { Response412Error } from '../errors/response412Error';

export class MerchantDetailsController extends BaseController {
  /**
   * Merchant Details
   *
   * @param body
   * @return Response from the API call
   */
  async merchantDetails(
    body: V1WalletProviderMerchantDetailsRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ResponseMerchantDetails>> {
    const req = this.createRequest(
      'POST',
      '/v1/wallet-provider/merchant-details'
    );
    const mapped = req.prepareArgs({
      body: [body, v1WalletProviderMerchantDetailsRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(401, Response401tokenError, 'Unauthorized');
    req.throwOn(412, Response412Error, 'Precondition Failed');
    req.authenticate([{ userId: true, userApiKey: true, developerId: true }]);
    return req.callAsJson(responseMerchantDetailsSchema, requestOptions);
  }
}
