/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { EmailEnum, emailEnumSchema } from '../models/emailEnum';
import { Expand14Enum, expand14EnumSchema } from '../models/expand14Enum';
import { Expand15Enum, expand15EnumSchema } from '../models/expand15Enum';
import { Field36Enum, field36EnumSchema } from '../models/field36Enum';
import { FilterBy, filterBySchema } from '../models/filterBy';
import { Format1Enum, format1EnumSchema } from '../models/format1Enum';
import { Order20, order20Schema } from '../models/order20';
import { Page, pageSchema } from '../models/page';
import {
  ResponsePaylink,
  responsePaylinkSchema,
} from '../models/responsePaylink';
import {
  ResponsePaylinksCollection,
  responsePaylinksCollectionSchema,
} from '../models/responsePaylinksCollection';
import { SmsEnum, smsEnumSchema } from '../models/smsEnum';
import {
  V1PaylinksRequest,
  v1PaylinksRequestSchema,
} from '../models/v1PaylinksRequest';
import {
  V1PaylinksRequest1,
  v1PaylinksRequest1Schema,
} from '../models/v1PaylinksRequest1';
import { array, optional, string } from '../schema';
import { BaseController } from './baseController';
import { Response401tokenError } from '../errors/response401tokenError';
import { Response412Error } from '../errors/response412Error';

export class PaylinksController extends BaseController {
  /**
   * @param body
   * @param expand       Most endpoints in the API have a way to retrieve extra data
   *                                                 related to the current record being retrieved. For example, if the
   *                                                 API request is for the accountvaults endpoint, and the end user
   *                                                 also needs to know which contact the token belongs to, this data
   *                                                 can be returned in the accountvaults endpoint request.
   * @return Response from the API call
   */
  async createANewPaylink(
    body: V1PaylinksRequest,
    expand?: Expand14Enum[],
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ResponsePaylink>> {
    const req = this.createRequest('POST', '/v1/paylinks');
    const mapped = req.prepareArgs({
      body: [body, v1PaylinksRequestSchema],
      expand: [expand, optional(array(expand14EnumSchema))],
    });
    req.header('Content-Type', 'application/json');
    req.query('expand', mapped.expand);
    req.json(mapped.body);
    req.throwOn(401, Response401tokenError, 'Unauthorized');
    req.throwOn(412, Response412Error, 'Precondition Failed');
    req.authenticate([{ userId: true, userApiKey: true, developerId: true }]);
    return req.callAsJson(responsePaylinkSchema, requestOptions);
  }

  /**
   * @param page       Use this field to specify paginate your results, by using page size and
   *                                     number. You can use one of the following methods: >/endpoint?page={ "number":
   *                                     1, "size": 50 } > >/endpoint?page[number]=1&page[size]=50 >
   * @param order      Criteria used in query string parameters to order results.  Most fields from
   *                                     the endpoint results can be used as a `key`.  Unsupported fields or operators
   *                                     will return a `412`.  Must be encoded, or use syntax that does not require
   *                                     encoding. >/endpoint?order[0][key]=created_ts&order[0][operator]=asc >
   *                                     >/endpoint?order=[{ "key": "created_ts", "operator": "asc"}] > >/endpoint?
   *                                     order=[{ "key": "balance", "operator": "desc"},{ "key": "created_ts",
   *                                     "operator": "asc"}] >
   * @param filterBy   Filter criteria that can be used in query string parameters.  Most fields
   *                                     from the endpoint results can be used as a `key`.  Unsupported fields or
   *                                     operators will return a `412`. Must be encoded, or use syntax that does not
   *                                     require encoding. >?
   *                                     filter_by[0][key]=first_name&filter_by[0][operator]==&filter_by[0][value]=Stev
   *                                     e > >/endpoint?filter_by=[{ "key": "first_name", "operator": "=", "value":
   *                                     "Fred" }] > >/endpoint?filter_by=[{ "key": "account_type", "operator": "=",
   *                                     "value": "VISA" }] > >/endpoint?filter_by=[{ "key": "created_ts", "operator":
   *                                     ">=", "value": "946702799" }, { "key": "created_ts", "operator": "<=", value:
   *                                     "1695061891" }] > >/endpoint?filter_by=[{ "key": "last_name", "operator": "IN",
   *                                     "value": "Williams,Brown,Allman" }] >
   * @param expand     Most endpoints in the API have a way to retrieve extra data related to the
   *                                     current record being retrieved. For example, if the API request is for the
   *                                     accountvaults endpoint, and the end user also needs to know which contact the
   *                                     token belongs to, this data can be returned in the accountvaults endpoint
   *                                     request.
   * @param format     Reporting format, valid values: csv, tsv
   * @param typeahead  You can use any `field_name` from this endpoint results to order the list
   *                                     using the value provided as filter for the same `field_name`. It will be
   *                                     ordered using the following rules: 1) Exact match, 2) Starts with, 3) Contains.
   *                                     >/endpoint?filter={ "field_name": "Value" }&_typeahead=field_name >
   * @param fields     You can use any `field_name` from this endpoint results to filter the list of
   *                                     fields returned on the response.
   * @return Response from the API call
   */
  async listAllPaylinks(
    page?: Page,
    order?: Order20[],
    filterBy?: FilterBy[],
    expand?: Expand15Enum[],
    format?: Format1Enum,
    typeahead?: string,
    fields?: Field36Enum[],
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ResponsePaylinksCollection>> {
    const req = this.createRequest('GET', '/v1/paylinks');
    const mapped = req.prepareArgs({
      page: [page, optional(pageSchema)],
      order: [order, optional(array(order20Schema))],
      filterBy: [filterBy, optional(array(filterBySchema))],
      expand: [expand, optional(array(expand15EnumSchema))],
      format: [format, optional(format1EnumSchema)],
      typeahead: [typeahead, optional(string())],
      fields: [fields, optional(array(field36EnumSchema))],
    });
    req.query('page', mapped.page);
    req.query('order', mapped.order);
    req.query('filter_by', mapped.filterBy);
    req.query('expand', mapped.expand);
    req.query('_format', mapped.format);
    req.query('_typeahead', mapped.typeahead);
    req.query('fields', mapped.fields);
    req.throwOn(401, Response401tokenError, 'Unauthorized');
    req.authenticate([{ userId: true, userApiKey: true, developerId: true }]);
    return req.callAsJson(responsePaylinksCollectionSchema, requestOptions);
  }

  /**
   * @param paylinkId  Paylink Id
   * @return Response from the API call
   */
  async deletePaylink(
    paylinkId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ResponsePaylink>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ paylinkId: [paylinkId, string()] });
    req.appendTemplatePath`/v1/paylinks/${mapped.paylinkId}`;
    req.throwOn(401, Response401tokenError, 'Unauthorized');
    req.authenticate([{ userId: true, userApiKey: true, developerId: true }]);
    return req.callAsJson(responsePaylinkSchema, requestOptions);
  }

  /**
   * @param paylinkId  Paylink Id
   * @param expand     Most endpoints in the API have a way to retrieve extra data related to the
   *                                     current record being retrieved. For example, if the API request is for the
   *                                     accountvaults endpoint, and the end user also needs to know which contact the
   *                                     token belongs to, this data can be returned in the accountvaults endpoint
   *                                     request.
   * @param fields     You can use any `field_name` from this endpoint results to filter the list of
   *                                     fields returned on the response.
   * @return Response from the API call
   */
  async viewSinglePaylink(
    paylinkId: string,
    expand?: Expand15Enum[],
    fields?: Field36Enum[],
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ResponsePaylink>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      paylinkId: [paylinkId, string()],
      expand: [expand, optional(array(expand15EnumSchema))],
      fields: [fields, optional(array(field36EnumSchema))],
    });
    req.query('expand', mapped.expand);
    req.query('fields', mapped.fields);
    req.appendTemplatePath`/v1/paylinks/${mapped.paylinkId}`;
    req.throwOn(401, Response401tokenError, 'Unauthorized');
    req.authenticate([{ userId: true, userApiKey: true, developerId: true }]);
    return req.callAsJson(responsePaylinkSchema, requestOptions);
  }

  /**
   * @param paylinkId    Paylink Id
   * @param body
   * @param expand       Most endpoints in the API have a way to retrieve extra data
   *                                                  related to the current record being retrieved. For example, if
   *                                                  the API request is for the accountvaults endpoint, and the end
   *                                                  user also needs to know which contact the token belongs to, this
   *                                                  data can be returned in the accountvaults endpoint request.
   * @return Response from the API call
   */
  async updatePaylink(
    paylinkId: string,
    body: V1PaylinksRequest1,
    expand?: Expand14Enum[],
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ResponsePaylink>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      paylinkId: [paylinkId, string()],
      body: [body, v1PaylinksRequest1Schema],
      expand: [expand, optional(array(expand14EnumSchema))],
    });
    req.header('Content-Type', 'application/json');
    req.query('expand', mapped.expand);
    req.json(mapped.body);
    req.appendTemplatePath`/v1/paylinks/${mapped.paylinkId}`;
    req.throwOn(401, Response401tokenError, 'Unauthorized');
    req.throwOn(412, Response412Error, 'Precondition Failed');
    req.authenticate([{ userId: true, userApiKey: true, developerId: true }]);
    return req.callAsJson(responsePaylinkSchema, requestOptions);
  }

  /**
   * @param paylinkId  Paylink Id
   * @param expand     Most endpoints in the API have a way to retrieve extra data related to the
   *                                     current record being retrieved. For example, if the API request is for the
   *                                     accountvaults endpoint, and the end user also needs to know which contact the
   *                                     token belongs to, this data can be returned in the accountvaults endpoint
   *                                     request.
   * @param email      Resend Email
   * @param sms        Resend SMS
   * @return Response from the API call
   */
  async resendPaylink(
    paylinkId: string,
    expand?: Expand14Enum[],
    email?: EmailEnum,
    sms?: SmsEnum,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ResponsePaylink>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      paylinkId: [paylinkId, string()],
      expand: [expand, optional(array(expand14EnumSchema))],
      email: [email, optional(emailEnumSchema)],
      sms: [sms, optional(smsEnumSchema)],
    });
    req.query('expand', mapped.expand);
    req.query('email', mapped.email);
    req.query('sms', mapped.sms);
    req.appendTemplatePath`/v1/paylinks/${mapped.paylinkId}/resend`;
    req.throwOn(401, Response401tokenError, 'Unauthorized');
    req.authenticate([{ userId: true, userApiKey: true, developerId: true }]);
    return req.callAsJson(responsePaylinkSchema, requestOptions);
  }
}
