/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AccountType16Enum
 */
export enum AccountType16Enum {
  Checking = 'checking',
  Savings = 'savings',
}

/**
 * Schema for AccountType16Enum
 */
export const accountType16EnumSchema: Schema<AccountType16Enum> = stringEnum(
  AccountType16Enum
);
