/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

export interface AccountVaultCauLog {
  /** Token CAU Log ID */
  id?: string;
  /** Product Transaction ID */
  productTransactionId?: string | null;
  /** Token ID */
  accountVaultId?: string | null;
  /** Created Time Stamp */
  createdTs?: number | null;
  /** User ID Created the register */
  createdUserId?: string | null;
  [key: string]: unknown;
}

export const accountVaultCauLogSchema: Schema<AccountVaultCauLog> = expandoObject(
  {
    id: ['id', optional(string())],
    productTransactionId: [
      'product_transaction_id',
      optional(nullable(string())),
    ],
    accountVaultId: ['account_vault_id', optional(nullable(string()))],
    createdTs: ['created_ts', optional(nullable(number()))],
    createdUserId: ['created_user_id', optional(nullable(string()))],
  }
);
