/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AchSecCode3Enum
 */
export enum AchSecCode3Enum {
  WEB = 'WEB',
  CCD = 'CCD',
  PPD = 'PPD',
  C21 = 'C21',
  POP = 'POP',
  TEL = 'TEL',
}

/**
 * Schema for AchSecCode3Enum
 */
export const achSecCode3EnumSchema: Schema<AchSecCode3Enum> = stringEnum(
  AchSecCode3Enum
);
