/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  expandoObject,
  nullable,
  optional,
  Schema,
  string,
} from '../schema';

export interface Addon {
  /** Title */
  title?: string;
  /** Secret */
  secret?: string;
  /** Iframe URL */
  iframeUrl?: string;
  /** Location Setup URL */
  locationSetupUrl?: string | null;
  /** User Setup URL */
  userSetupUrl?: string | null;
  /** Encrypt URL Params */
  encryptUrlParams?: boolean;
  [key: string]: unknown;
}

export const addonSchema: Schema<Addon> = expandoObject({
  title: ['title', optional(string())],
  secret: ['secret', optional(string())],
  iframeUrl: ['iframe_url', optional(string())],
  locationSetupUrl: ['location_setup_url', optional(nullable(string()))],
  userSetupUrl: ['user_setup_url', optional(nullable(string()))],
  encryptUrlParams: ['encrypt_url_params', optional(boolean())],
});
