/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, nullable, optional, Schema, string } from '../schema';
import { CountryEnum, countryEnumSchema } from './countryEnum';

/** Address of contact */
export interface Address {
  /** City of contact */
  city?: string | null;
  /** State of contact */
  state?: string | null;
  /** Postal code of contact */
  postalCode?: string | null;
  /** An alpha 2 format country code of US or CA. */
  country?: CountryEnum | null;
  /** Street of contact */
  street?: string | null;
  [key: string]: unknown;
}

export const addressSchema: Schema<Address> = expandoObject({
  city: ['city', optional(nullable(string()))],
  state: ['state', optional(nullable(string()))],
  postalCode: ['postal_code', optional(nullable(string()))],
  country: ['country', optional(nullable(countryEnumSchema))],
  street: ['street', optional(nullable(string()))],
});
