/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AddressTypeEnum
 */
export enum AddressTypeEnum {
  Location = 'location',
  Mailing = 'mailing',
  Corporate = 'corporate',
}

/**
 * Schema for AddressTypeEnum
 */
export const addressTypeEnumSchema: Schema<AddressTypeEnum> = stringEnum(
  AddressTypeEnum
);
