/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, nullable, optional, Schema, string } from '../schema';
import { CountryEnum, countryEnumSchema } from './countryEnum';

/** Address */
export interface Address2 {
  /** City name */
  city?: string | null;
  /** State name */
  state?: string | null;
  /** Postal code */
  postalCode?: string | null;
  /** An alpha 2 format country code of US or CA. */
  country?: CountryEnum | null;
  /** Street */
  street?: string | null;
  [key: string]: unknown;
}

export const address2Schema: Schema<Address2> = expandoObject({
  city: ['city', optional(nullable(string()))],
  state: ['state', optional(nullable(string()))],
  postalCode: ['postal_code', optional(nullable(string()))],
  country: ['country', optional(nullable(countryEnumSchema))],
  street: ['street', optional(nullable(string()))],
});
