/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, nullable, optional, Schema, string } from '../schema';

/** The Alternative Bank Account. */
export interface AltBankAccount {
  /** Nine-digit Bank routing number. */
  routingNumber?: string | null;
  /** Bank account number. */
  accountNumber?: string | null;
  /** Name on bank account. */
  accountHolderName?: string | null;
  /** Deposit type. */
  depositType?: string | null;
  [key: string]: unknown;
}

export const altBankAccountSchema: Schema<AltBankAccount> = expandoObject({
  routingNumber: ['routing_number', optional(nullable(string()))],
  accountNumber: ['account_number', optional(nullable(string()))],
  accountHolderName: ['account_holder_name', optional(nullable(string()))],
  depositType: ['deposit_type', optional(nullable(string()))],
});
