/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AvsEnum
 */
export enum AvsEnum {
  BAD = 'BAD',
  ZIP = 'ZIP',
  STREET = 'STREET',
  GOOD = 'GOOD',
  UNKNOWN = 'UNKNOWN',
}

/**
 * Schema for AvsEnum
 */
export const avsEnumSchema: Schema<AvsEnum> = stringEnum(AvsEnum);
