/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  expandoObject,
  optional,
  Schema,
  string,
} from '../schema';
import {
  AccountType12Enum,
  accountType12EnumSchema,
} from './accountType12Enum';

/**
 * Array of bank account objects.
 * >One account with “deposit_type” of primary is required. Maximum of two accounts are allowed.
 * >
 */
export interface BankAccount1 {
  /** Account holder name. */
  accountHolderName: string;
  /** Nine-digit Bank routing number. */
  routingNumber: string;
  /** Account number. */
  accountNumber: string;
  /**
   * Flag indicating whether or not the account is the primary account. Only one account can be marked as primary.
   * >Indicates that the account should be the primary account for the merchant. One and only one account may be set to true.
   * >
   */
  isPrimary?: boolean;
  /** Account type. Either "checking" or "savings" */
  accountType: AccountType12Enum;
  /** Array of deposit types. ('fees', 'adjustments', 'returns') */
  altDepositTypes?: string[];
  [key: string]: unknown;
}

export const bankAccount1Schema: Schema<BankAccount1> = expandoObject({
  accountHolderName: ['account_holder_name', string()],
  routingNumber: ['routing_number', string()],
  accountNumber: ['account_number', string()],
  isPrimary: ['is_primary', optional(boolean())],
  accountType: ['account_type', accountType12EnumSchema],
  altDepositTypes: ['alt_deposit_types', optional(array(string()))],
});
