/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  expandoObject,
  number,
  optional,
  Schema,
  string,
} from '../schema';
import {
  ChallengeWindowSizeEnum,
  challengeWindowSizeEnumSchema,
} from './challengeWindowSizeEnum';

/**
 * Contains browser information.
 * This field is required when device_channel=02 (BRW).
 */
export interface BrowserInformation {
  /**
   * Exact content of the HTTP accept headers as sent to the 3DS Requestor from the Cardholder's browser. This field is limited to maximum 2048 characters  and if the total length exceeds the limit, the 3DS Server truncates the excess portion.
   *  This field is required for requests where device_channel=02 (BRW).
   */
  browserAcceptHeader?: string;
  /**
   * Boolean that represents the ability of the cardholder browser to execute Java. Value is returned from the navigator.javaEnabled property.
   * Depending on the message version, the field is required for requests:
   * - with message version = 2.1.0 and device_channel = 02 (BRW).
   * - with message version = 2.2.0 and device_channel = 02 (BRW) and browser_javascript_enabled = true.
   */
  browserJavaEnabled?: boolean;
  /**
   * Value representing the browser language as defined in IETF BCP47.
   * Until EMV 3DS 2.2.0:
   * The value is limited to 1-8 characters. If the value exceeds 8 characters, it will be truncated to a semantically valid value, if possible. The value is returned from navigator.language property.
   * This field is required for requests where device_channel = 02 (BRW).
   * In other cases this field is optional.
   * Starting from EMV 3DS 2.3.1:
   * The value is limited to 35 characters. If the value exceeds 35 characters, it will be truncated to a semantically valid value, if possible. The value is returned from navigator.language property.
   * This field is required for requests where device_channel = 02 (BRW) and browser_javascript_enabled = true.
   * In other cases this field is optional.
   */
  browserLanguage?: string;
  /**
   * Value representing the bit depth of the color palette for displaying images, in bits per pixel. Obtained from Cardholder browser using the screen.colorDepth property. The field is limited to 1-2 characters.
   * If the value is not in the accepted values, it will be resolved to the first accepted value lower from the one provided.
   * Depending on the message version, the field is required for requests:
   * - with message version = 2.1.0 and device_channel = 02 (BRW).
   * - with message version = 2.2.0 and device_channel = 02 (BRW) and browser_javascript_enabled = true.
   * >1 - 1 bit
   * >
   * >4 - 4 bits
   * >
   * >8 - 8 bits
   * >
   * >15 - 15 bits
   * >
   * >16 - 16 bits
   * >
   * >24 - 24 bits
   * >
   * >32 - 32 bits
   * >
   * >48 - 48 bits
   * >
   */
  browserColorDepth?: string;
  /**
   * Total height of the Cardholder's screen in pixels. Value is returned from the screen.height property. The value is limited to 1-6 characters.
   * Depending on the message version, the field is required for requests:
   * - with message version = 2.1.0 and device_channel = 02 (BRW).
   * - with message version = 2.2.0 and device_channel = 02 (BRW) and browserJavascripbrowser_javascript_enabledtEnabled = true.
   */
  browserScreenHeight?: number;
  /**
   * Total width of the Cardholder's screen in pixels. Value is returned from the screen.width property. The value is limited to 1-6 characters.
   * Depending on the message version, the field is required for requests:
   * - with message version = 2.1.0 and device_channel = 02 (BRW).
   * - with message version = 2.2.0 and device_channel = 02 (BRW) and browser_javascript_enabled = true.
   */
  browserScreenWidth?: number;
  /**
   * Time difference between UTC time and the Cardholder browser local time, in minutes. The field is limited to 1-5 characters where the values is returned from the getTimezoneOffset() method.
   * Depending on the message version, the field is required for requests:
   * - with message version = 2.1.0 and device_channel = 02 (BRW).
   * - with message version = 2.2.0 and device_channel = 02 (BRW) and browser_javascript_enabled = true.
   */
  browserTz?: number;
  /**
   * Exact content of the HTTP user-agent header. The field is limited to maximum 2048 caracters. If the total length of the User-Agent sent by the browser exceeds 2048 characters, the 3DS Server truncates the excess portion.
   * This field is required for requests where device_channel = 02 (BRW).
   */
  browserUserAgent?: string;
  /**
   * Dimensions of the challenge window that has been displayed to the Cardholder. The ACS shall reply with content that is formatted to appropriately render in this window to provide the best possible user experience.
   * Preconfigured sizes are width X height in pixels of the window displayed in the Cardholder browser window. This is used only to prepare the CReq request and it is not part of the AReq flow. If not present it will be omitted.
   * However, when sending the Challenge Request, this field is required when device_channel = 02 (BRW).
   * >01 - 250 x 400
   * >
   * >02 - 390 x 400
   * >
   * >03 - 500 x 600
   * >
   * >04 - 600 x 400
   * >
   * >05 - Full screen
   * >
   */
  challengeWindowSize?: ChallengeWindowSizeEnum;
  /**
   * Boolean that represents the ability of the cardholder browser to execute JavaScript.
   * This field is required for requests where device_channel = 02 (BRW).
   * Available for supporting EMV 3DS 2.2.0 and later versions.
   */
  browserJavascriptEnabled?: boolean;
  /**
   * Value representing the browser language preference present in the http header, as defined in IETF BCP 47.
   * The value is limited to 1-99 elements. Each element should contain a maximum of 100 characters.
   * This field is required for requests where device_channel = 02 (BRW).
   * Available for supporting EMV 3DS 2.3.1 and later versions.
   */
  acceptLanguage?: string[];
  [key: string]: unknown;
}

export const browserInformationSchema: Schema<BrowserInformation> = expandoObject(
  {
    browserAcceptHeader: ['browser_accept_header', optional(string())],
    browserJavaEnabled: ['browser_java_enabled', optional(boolean())],
    browserLanguage: ['browser_language', optional(string())],
    browserColorDepth: ['browser_color_depth', optional(string())],
    browserScreenHeight: ['browser_screen_height', optional(number())],
    browserScreenWidth: ['browser_screen_width', optional(number())],
    browserTz: ['browser_tz', optional(number())],
    browserUserAgent: ['browser_user_agent', optional(string())],
    challengeWindowSize: [
      'challenge_window_size',
      optional(challengeWindowSizeEnumSchema),
    ],
    browserJavascriptEnabled: [
      'browser_javascript_enabled',
      optional(boolean()),
    ],
    acceptLanguage: ['accept_language', optional(array(string()))],
  }
);
