/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { AddressMatchEnum, addressMatchEnumSchema } from './addressMatchEnum';
import { BillingAddress24, billingAddress24Schema } from './billingAddress24';
import { HomePhone, homePhoneSchema } from './homePhone';
import { MobilePhone, mobilePhoneSchema } from './mobilePhone';
import { ShippingAddress, shippingAddressSchema } from './shippingAddress';
import { WorkPhone, workPhoneSchema } from './workPhone';

/** Contains information for the Cardholder. This field is required unless market or regional mandate restricts sending this information. */
export interface Cardholder {
  /**
   * Indicates whether the Cardholder Shipping Address and Cardholder Billing Address are the same.
   *  If the field is not set and the shipping and billing addresses are the same, the 3DS Server will set the value to Y. Otherwise, the value will not be changed.
   * >Y - Shipping Address matches Billing Address
   * >
   * >N - Shipping Address does not match Billing Address
   * >
   */
  addressMatch?: AddressMatchEnum;
  /** Cardholder billing address object */
  billingAddress?: BillingAddress24;
  /**
   * The email address associated with the account that is either entered by the Cardholder, or is on file with the 3DS Requestor. This field shall meet requirements of Section 3.4 of IETF RFC 5322.
   * This field is required unless market or regional mandate restricts sending this information.
   */
  email?: string;
  /**
   * The home phone provided by the Cardholder. Refer to ITU-E.164 for additional information on format and length.
   * This field is required if available, unless market or regional mandate restricts sending this information.
   */
  homePhone?: HomePhone;
  /**
   * The mobile phone provided by the Cardholder. Refer to ITU-E.164 for additional information on format and length.
   * This field is required if available, unless market or regional mandate restricts sending this information.
   */
  mobilePhone?: MobilePhone;
  /**
   * The work phone provided by the Cardholder. Refer to ITU-E.164 for additional information on format and length.
   * This field is required if available, unless market or regional mandate restricts sending this information.
   */
  workPhone?: WorkPhone;
  /**
   * Name of the Cardholder.
   * This field is required unless market or regional mandate restricts sending this information.
   */
  cardholderName?: string;
  /** Cardholder shipping address object */
  shippingAddress?: ShippingAddress;
  /**
   * Tax ID is the Cardholder's tax identification.
   * This field is required depending on the rules provided by the Directory Server.
   * Available for supporting EMV 3DS 2.3.1 and later versions.
   */
  taxId?: string;
  [key: string]: unknown;
}

export const cardholderSchema: Schema<Cardholder> = expandoObject({
  addressMatch: ['address_match', optional(addressMatchEnumSchema)],
  billingAddress: [
    'billing_address',
    optional(lazy(() => billingAddress24Schema)),
  ],
  email: ['email', optional(string())],
  homePhone: ['home_phone', optional(lazy(() => homePhoneSchema))],
  mobilePhone: ['mobile_phone', optional(lazy(() => mobilePhoneSchema))],
  workPhone: ['work_phone', optional(lazy(() => workPhoneSchema))],
  cardholderName: ['cardholder_name', optional(string())],
  shippingAddress: [
    'shipping_address',
    optional(lazy(() => shippingAddressSchema)),
  ],
  taxId: ['tax_id', optional(string())],
});
