/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { AccountInfo, accountInfoSchema } from './accountInfo';
import { SchemeIdEnum, schemeIdEnumSchema } from './schemeIdEnum';

/** Contains information for the Cardholder Account. */
export interface CardholderAccount {
  /**
   * Expiry date of the PAN or token supplied to the 3DS Requestor by the Cardholder. The field has 4 characters in a format YYMM.
   * The requirements of the presence of this field are DS specific.
   */
  expireDate?: string;
  /** This field contains additional information about the Cardholder's account provided by the 3DS Requestor. The field is optional but recommended to include. */
  accountInfo?: AccountInfo;
  /** Account number that will be used in the authorization request for payment transactions. May be represented by PAN or token. */
  accountNumber: string;
  /** ID for the scheme to which the Cardholder's acctNumber belongs to. It will be used to identify the Scheme from the 3DS Server configuration. */
  schemeId: SchemeIdEnum;
  /** Additional information about the account optionally provided by the 3DS Requestor. */
  accountId?: string;
  /** Three or four-digit security code printed on the card. This field is required depending on the rules provided by the Directory Server. Available for supporting EMV 3DS 2.3.1 and later versions. */
  cvv?: string;
  [key: string]: unknown;
}

export const cardholderAccountSchema: Schema<CardholderAccount> = expandoObject(
  {
    expireDate: ['expire_date', optional(string())],
    accountInfo: ['account_info', optional(lazy(() => accountInfoSchema))],
    accountNumber: ['account_number', string()],
    schemeId: ['scheme_id', schemeIdEnumSchema],
    accountId: ['account_id', optional(string())],
    cvv: ['cvv', optional(string())],
  }
);
