/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema } from '../schema';
import { Method53Enum, method53EnumSchema } from './method53Enum';
import { Values58Enum, values58EnumSchema } from './values58Enum';

export interface Conditions191 {
  method?: Method53Enum;
  values?: Values58Enum;
  [key: string]: unknown;
}

export const conditions191Schema: Schema<Conditions191> = expandoObject({
  method: ['method', optional(method53EnumSchema)],
  values: ['values', optional(values58EnumSchema)],
});
