/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema } from '../schema';
import { Method5Enum, method5EnumSchema } from './method5Enum';
import { Values5Enum, values5EnumSchema } from './values5Enum';

export interface Conditions41 {
  method?: Method5Enum;
  values?: Values5Enum;
  [key: string]: unknown;
}

export const conditions41Schema: Schema<Conditions41> = expandoObject({
  method: ['method', optional(method5EnumSchema)],
  values: ['values', optional(values5EnumSchema)],
});
