/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema, string } from '../schema';

export interface Data16 {
  /** JWT used to initialize the card reader */
  token?: string;
  [key: string]: unknown;
}

export const data16Schema: Schema<Data16> = expandoObject({
  token: ['token', optional(string())],
});
