/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

export interface Data {
  /** A [UUID v4](https://datatracker.ietf.org/doc/html/rfc4122) that's unique for the Async Request */
  code?: string;
  /** The @type from the original request. */
  type?: string;
  /** After a sucessfully processing, the system will fill with the final ID for the document */
  id?: string;
  /** The current percentage progress */
  progress?: number;
  /** In case of error processing, it will contain the error details */
  error?: string | null;
  /** The date (in [Epoch Time](https://en.wikipedia.org/wiki/Unix_time)) this status register is set to expire. Usually 30 days after the request. */
  ttl?: bigint;
  [key: string]: unknown;
}

export const dataSchema: Schema<Data> = expandoObject({
  code: ['code', optional(string())],
  type: ['type', optional(string())],
  id: ['id', optional(string())],
  progress: ['progress', optional(number())],
  error: ['error', optional(nullable(string()))],
  ttl: ['ttl', optional(bigint())],
});
