/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, nullable, optional, Schema, string } from '../schema';

export interface Data7 {
  /** Used to associate the Ticket with a Contact. */
  contactId?: string | null;
  /** Used to associate the Ticket with a Contact. */
  contactApiId?: string | null;
  /** A valid Location Id associated with the Contact for this Ticket */
  locationId?: string;
  /** Include a product_transaction_id to respect it's cvv and address field settings when creating a ticket.  These settings are enforced at the ticket creation level only. */
  productTransactionId?: string | null;
  /** A custom text message that displays after the ticket is created. */
  message?: string | null;
  /**
   * A JWT to be used to create the elements.
   * > This is a one-time only use token.
   * > Do not store for long term use, it expires after 48 hours.
   */
  clientToken?: string;
  [key: string]: unknown;
}

export const data7Schema: Schema<Data7> = expandoObject({
  contactId: ['contact_id', optional(nullable(string()))],
  contactApiId: ['contact_api_id', optional(nullable(string()))],
  locationId: ['location_id', optional(string())],
  productTransactionId: [
    'product_transaction_id',
    optional(nullable(string())),
  ],
  message: ['message', optional(nullable(string()))],
  clientToken: ['client_token', optional(string())],
});
