/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema, string } from '../schema';

export interface Data32 {
  /** User Api Key */
  userApiKey?: string;
  [key: string]: unknown;
}

export const data32Schema: Schema<Data32> = expandoObject({
  userApiKey: ['user_api_key', optional(string())],
});
