/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema';

/**
 * Enum for DeliveryMethodEnum
 */
export enum DeliveryMethodEnum {
  Enum0 = 0,
  Enum1 = 1,
  Enum2 = 2,
  Enum3 = 3,
}

/**
 * Schema for DeliveryMethodEnum
 */
export const deliveryMethodEnumSchema: Schema<DeliveryMethodEnum> = numberEnum(
  DeliveryMethodEnum
);
