/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DeviceChannelEnum
 */
export enum DeviceChannelEnum {
  Enum02 = '02',
  Enum03 = '03',
}

/**
 * Schema for DeviceChannelEnum
 */
export const deviceChannelEnumSchema: Schema<DeviceChannelEnum> = stringEnum(
  DeviceChannelEnum
);
