/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EFormatEnum
 */
export enum EFormatEnum {
  Ksn = 'ksn',
  Ksnpin = 'ksnpin',
  Idtech = 'idtech',
  Magnesafe = 'magnesafe',
  Magtek = 'magtek',
  Fulltrack = 'fulltrack',
  Keyed = 'keyed',
}

/**
 * Schema for EFormatEnum
 */
export const eFormatEnumSchema: Schema<EFormatEnum> = stringEnum(EFormatEnum);
