/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema';

/**
 * Enum for EmailEnum
 */
export enum EmailEnum {
  Enum0 = 0,
  Enum1 = 1,
}

/**
 * Schema for EmailEnum
 */
export const emailEnumSchema: Schema<EmailEnum> = numberEnum(EmailEnum);
