/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Expand1Enum
 */
export enum Expand1Enum {
  ReceivedEmails = 'received_emails',
  IsDeletable = 'is_deletable',
  Location = 'location',
  User = 'user',
  Recurrings = 'recurrings',
  EmailBlacklist = 'email_blacklist',
  SmsBlacklist = 'sms_blacklist',
  Changelogs = 'changelogs',
  PostbackLogs = 'postback_logs',
  CreatedUser = 'created_user',
  Parent = 'parent',
  Children = 'children',
}

/**
 * Schema for Expand1Enum
 */
export const expand1EnumSchema: Schema<Expand1Enum> = stringEnum(Expand1Enum);
