/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Expand41Enum
 */
export enum Expand41Enum {
  Location = 'location',
  Contact = 'contact',
  CreatedUser = 'created_user',
}

/**
 * Schema for Expand41Enum
 */
export const expand41EnumSchema: Schema<Expand41Enum> = stringEnum(
  Expand41Enum
);
