/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Expand8Enum
 */
export enum Expand8Enum {
  CreatedUser = 'created_user',
  Location = 'location',
  Terminal = 'terminal',
  Changelogs = 'changelogs',
  Signature = 'signature',
  ReasonCode = 'reason_code',
}

/**
 * Schema for Expand8Enum
 */
export const expand8EnumSchema: Schema<Expand8Enum> = stringEnum(Expand8Enum);
