/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Expand108Enum
 */
export enum Expand108Enum {
  ReceivedEmails = 'received_emails',
  FeatureFlags = 'feature_flags',
  PrimaryLocation = 'primary_location',
  Locations = 'locations',
  Contact = 'contact',
  IsDeletable = 'isDeletable',
  ActiveNotificationAlerts = 'active_notification_alerts',
  LocationUsers = 'location_users',
  AuthRoles = 'auth_roles',
  ContactId = 'contact_id',
  Changelogs = 'changelogs',
  Resources = 'resources',
  Domain = 'domain',
  CreatedUser = 'created_user',
  LocationMarketplaces = 'location_marketplaces',
  EmailBlacklist = 'email_blacklist',
  Helppage = 'helppage',
}

/**
 * Schema for Expand108Enum
 */
export const expand108EnumSchema: Schema<Expand108Enum> = stringEnum(
  Expand108Enum
);
