/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Expand10Enum
 */
export enum Expand10Enum {
  Users = 'users',
  IsDeletable = 'is_deletable',
  BrandingDomain = 'branding_domain',
  ProductInvoice = 'product_invoice',
  ProductFiles = 'product_files',
  Parent = 'parent',
  CreatedUser = 'created_user',
  Changelogs = 'changelogs',
  ProductTransactions = 'product_transactions',
  Terminals = 'terminals',
  TerminalRouters = 'terminal_routers',
  DeveloperCompany = 'developer_company',
  DeveloperCompanyId = 'developer_company_id',
  Helppages = 'helppages',
  QuickInvoiceSetting = 'quick_invoice_setting',
  LocationBillingAccounts = 'location_billing_accounts',
  Marketplaces = 'marketplaces',
  Locationmarketplaces = 'locationmarketplaces',
  Addons = 'addons',
}

/**
 * Schema for Expand10Enum
 */
export const expand10EnumSchema: Schema<Expand10Enum> = stringEnum(
  Expand10Enum
);
