/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Expand114Enum
 */
export enum Expand114Enum {
  Postbacklogs = 'postbacklogs',
  BasicAuthUsername = 'basic_auth_username',
  BasicAuthPassword = 'basic_auth_password',
}

/**
 * Schema for Expand114Enum
 */
export const expand114EnumSchema: Schema<Expand114Enum> = stringEnum(
  Expand114Enum
);
