/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Expand44Enum
 */
export enum Expand44Enum {
  Location = 'location',
  Contact = 'contact',
  Transactions = 'transactions',
  ActiveRecurrings = 'activeRecurrings',
  IsDeletable = 'is_deletable',
  Signature = 'signature',
  CreatedUser = 'created_user',
  Changelogs = 'changelogs',
  AccountVaultCauLogs = 'account_vault_cau_logs',
  AccountVaultCauProductTransactions = 'account_vault_cau_product_transactions',
}

/**
 * Schema for Expand44Enum
 */
export const expand44EnumSchema: Schema<Expand44Enum> = stringEnum(
  Expand44Enum
);
