/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Field42Enum
 */
export enum Field42Enum {
  Signature = 'signature',
  Resource = 'resource',
  ResourceId = 'resource_id',
  Id = 'id',
  CreatedTs = 'created_ts',
  ModifiedTs = 'modified_ts',
  RawSignature = 'raw_signature',
}

/**
 * Schema for Field42Enum
 */
export const field42EnumSchema: Schema<Field42Enum> = stringEnum(Field42Enum);
