/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Field32Enum
 */
export enum Field32Enum {
  Id = 'id',
  CreatedTs = 'created_ts',
  ModifiedTs = 'modified_ts',
  AccountNumber = 'account_number',
  Address = 'address',
  BrandingDomainId = 'branding_domain_id',
  ContactEmailTrxReceiptDefault = 'contact_email_trx_receipt_default',
  DefaultAch = 'default_ach',
  DefaultCc = 'default_cc',
  EmailReplyTo = 'email_reply_to',
  Fax = 'fax',
  LocationApiId = 'location_api_id',
  LocationApiKey = 'location_api_key',
  LocationC1 = 'location_c1',
  LocationC2 = 'location_c2',
  LocationC3 = 'location_c3',
  Name = 'name',
  OfficePhone = 'office_phone',
  OfficeExtPhone = 'office_ext_phone',
  Tz = 'tz',
  ParentId = 'parent_id',
  ShowContactNotes = 'show_contact_notes',
  ShowContactFiles = 'show_contact_files',
  CreatedUserId = 'created_user_id',
  LocationType = 'location_type',
  ParentName = 'parent_name',
  TicketHashKey = 'ticket_hash_key',
  Parent = 'parent',
  Users = 'users',
  IsDeletable = 'is_deletable',
  Terminals = 'terminals',
  BrandingDomain = 'branding_domain',
  ProductInvoice = 'product_invoice',
  ProductFiles = 'product_files',
  CreatedUser = 'created_user',
  Changelogs = 'changelogs',
  ProductTransactions = 'product_transactions',
  TerminalRouters = 'terminal_routers',
  DeveloperCompany = 'developer_company',
  DeveloperCompanyId = 'developer_company_id',
  Helppages = 'helppages',
  QuickInvoiceSetting = 'quick_invoice_setting',
  LocationBillingAccounts = 'location_billing_accounts',
  Marketplaces = 'marketplaces',
  Locationmarketplaces = 'locationmarketplaces',
  Addons = 'addons',
  Relationship = 'relationship',
}

/**
 * Schema for Field32Enum
 */
export const field32EnumSchema: Schema<Field32Enum> = stringEnum(Field32Enum);
