/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Field40Enum
 */
export enum Field40Enum {
  AccountVaultId = 'account_vault_id',
  TokenId = 'token_id',
  ContactId = 'contact_id',
  AccountVaultApiId = 'account_vault_api_id',
  TokenApiId = 'token_api_id',
  Joi = '_joi',
  Active = 'active',
  Description = 'description',
  EndDate = 'end_date',
  InstallmentTotalCount = 'installment_total_count',
  Interval = 'interval',
  IntervalType = 'interval_type',
  LocationId = 'location_id',
  NotificationDays = 'notification_days',
  PaymentMethod = 'payment_method',
  ProductTransactionId = 'product_transaction_id',
  RecurringId = 'recurring_id',
  RecurringApiId = 'recurring_api_id',
  StartDate = 'start_date',
  Status = 'status',
  TransactionAmount = 'transaction_amount',
  TermsAgree = 'terms_agree',
  TermsAgreeIp = 'terms_agree_ip',
  RecurringC1 = 'recurring_c1',
  RecurringC2 = 'recurring_c2',
  RecurringC3 = 'recurring_c3',
  SendToProcAsRecur = 'send_to_proc_as_recur',
  Tags = 'tags',
  SecondaryAmount = 'secondary_amount',
  Currency = 'currency',
  Id = 'id',
  NextRunDate = 'next_run_date',
  CreatedTs = 'created_ts',
  ModifiedTs = 'modified_ts',
  RecurringTypeId = 'recurring_type_id',
  InstallmentAmountTotal = 'installment_amount_total',
  CreatedUserId = 'created_user_id',
  LogEmails = 'log_emails',
  Contact = 'contact',
  AccountVault = 'account_vault',
  CreatedUser = 'created_user',
  Signature = 'signature',
  PaymentSchedule = 'payment_schedule',
  Location = 'location',
  ProductTransaction = 'product_transaction',
  NextRunDateMin = 'next_run_date_min',
  NextRunDateMax = 'next_run_date_max',
  AllTags = 'all_tags',
  Changelogs = 'changelogs',
  Forecast = 'forecast',
  RecurringSplits = 'recurring_splits',
  Transactions = 'transactions',
}

/**
 * Schema for Field40Enum
 */
export const field40EnumSchema: Schema<Field40Enum> = stringEnum(Field40Enum);
