/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Field52Enum
 */
export enum Field52Enum {
  RejectedTransactionId = 'rejected_transaction_id',
  ReturnFee = 'return_fee',
  Id = 'id',
  RetryTransactionId = 'retry_transaction_id',
  ReturnFeeTransactionId = 'return_fee_transaction_id',
  CreatedTs = 'created_ts',
  CreatedUserId = 'created_user_id',
  RejectedTransaction = 'rejected_transaction',
  RetryTransaction = 'retry_transaction',
  ReturnFeeTransaction = 'return_fee_transaction',
  CreatedUser = 'created_user',
  Changelogs = 'changelogs',
}

/**
 * Schema for Field52Enum
 */
export const field52EnumSchema: Schema<Field52Enum> = stringEnum(Field52Enum);
