/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Format1Enum
 */
export enum Format1Enum {
  Csv = 'csv',
  Tsv = 'tsv',
}

/**
 * Schema for Format1Enum
 */
export const format1EnumSchema: Schema<Format1Enum> = stringEnum(Format1Enum);
