/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema';

/**
 * Enum for IiasIndEnum
 */
export enum IiasIndEnum {
  Enum0 = 0,
  Enum1 = 1,
  Enum2 = 2,
}

/**
 * Schema for IiasIndEnum
 */
export const iiasIndEnumSchema: Schema<IiasIndEnum> = numberEnum(IiasIndEnum);
