/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema } from '../schema';
import {
  Joi18Conditions,
  joi18ConditionsSchema,
} from './containers/joi18Conditions';

export interface Joi18 {
  conditions?: Joi18Conditions;
  [key: string]: unknown;
}

export const joi18Schema: Schema<Joi18> = expandoObject({
  conditions: ['conditions', optional(joi18ConditionsSchema)],
});
