/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string } from '../schema';

/** Array of KYC response objects. */
export interface KycResponseObject {
  /** KYC object value. */
  value: string;
  /** KYC oject type. */
  type: string;
  [key: string]: unknown;
}

export const kycResponseObjectSchema: Schema<KycResponseObject> = expandoObject(
  { value: ['value', string()], type: ['type', string()] }
);
