/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  expandoObject,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';
import { LineItem19, lineItem19Schema } from './lineItem19';
import { TaxExemptEnum, taxExemptEnumSchema } from './taxExemptEnum';

/** Level 3 data object */
export interface Level3Data5 {
  /** Code of the country where the goods are being shipped. */
  destinationCountryCode?: string | null;
  /** Fee amount associated with the import of the purchased goods ,Can accept Two (2) decimal places */
  dutyAmount?: number | null;
  /** Freight or shipping portion of the total transaction amount ,Can accept Two (2) decimal places. */
  freightAmount?: number | null;
  /** National tax for the transaction ,Can accept Two (2) decimal places. */
  nationalTax?: number | null;
  /** Sales tax for the transaction ,Can accept Two (2) decimal places. */
  salesTax?: number | null;
  /** Postal/ZIP code of the address from where the purchased goods are being shipped. */
  shipfromZipCode?: string | null;
  /** Postal/ZIP code of the address where purchased goods will be delivered. */
  shiptoZipCode?: string | null;
  /** Amount of any value added taxes ,Can accept Two (2) decimal places. */
  taxAmount?: number | null;
  /** Sales Tax Exempt. Allowed values: “1”, “0”. */
  taxExempt?: TaxExemptEnum | null;
  /** Array of line items in transaction */
  lineItems: LineItem19[];
  [key: string]: unknown;
}

export const level3Data5Schema: Schema<Level3Data5> = expandoObject({
  destinationCountryCode: [
    'destination_country_code',
    optional(nullable(string())),
  ],
  dutyAmount: ['duty_amount', optional(nullable(number()))],
  freightAmount: ['freight_amount', optional(nullable(number()))],
  nationalTax: ['national_tax', optional(nullable(number()))],
  salesTax: ['sales_tax', optional(nullable(number()))],
  shipfromZipCode: ['shipfrom_zip_code', optional(nullable(string()))],
  shiptoZipCode: ['shipto_zip_code', optional(nullable(string()))],
  taxAmount: ['tax_amount', optional(nullable(number()))],
  taxExempt: ['tax_exempt', optional(nullable(taxExemptEnumSchema))],
  lineItems: ['line_items', array(lazy(() => lineItem19Schema))],
});
