/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

export interface LineItem20 {
  /** Description of the item. */
  description: string;
  /** An international description code of the individual good or service being supplied. */
  commodityCode: string;
  /** Total discount amount applied against the line item total ,Can accept Two (2) decimal places. */
  discountAmount?: number | null;
  /** Used if city or multiple county taxes need to be broken out separately ,Can accept Two (2) decimal places. */
  otherTaxAmount?: number | null;
  /** Merchant-defined description code of the item. */
  productCode: string;
  /** Quantity of the item, can accept Four (4) decimal places. */
  quantity?: number | null;
  /** Amount of any value added taxes, can accept Two (2) decimal places. */
  taxAmount?: number | null;
  /** Tax rate used to calculate the sales tax amount, can accept 2 decimal places. */
  taxRate?: number | null;
  /** Units of measurement as used in international trade. (See Codes for Units of Measurement below for unit code abbreviations) */
  unitCode: string;
  /** Unit cost of the item ,Can accept Four (4) decimal places. */
  unitCost: number;
  [key: string]: unknown;
}

export const lineItem20Schema: Schema<LineItem20> = expandoObject({
  description: ['description', string()],
  commodityCode: ['commodity_code', string()],
  discountAmount: ['discount_amount', optional(nullable(number()))],
  otherTaxAmount: ['other_tax_amount', optional(nullable(number()))],
  productCode: ['product_code', string()],
  quantity: ['quantity', optional(nullable(number()))],
  taxAmount: ['tax_amount', optional(nullable(number()))],
  taxRate: ['tax_rate', optional(nullable(number()))],
  unitCode: ['unit_code', string()],
  unitCost: ['unit_cost', number()],
});
