/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema, string } from '../schema';
import { Type2Enum, type2EnumSchema } from './type2Enum';

/** Pagination page links */
export interface Links {
  /** Object type */
  type?: Type2Enum;
  /** Link to the first page */
  first?: string;
  /** Link to the previous page */
  previous?: string;
  /** Link to the next page */
  next?: string;
  /** Link to the last page */
  last?: string;
  [key: string]: unknown;
}

export const linksSchema: Schema<Links> = expandoObject({
  type: ['type', optional(type2EnumSchema)],
  first: ['first', optional(string())],
  previous: ['previous', optional(string())],
  next: ['next', optional(string())],
  last: ['last', optional(string())],
});
