/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';
import {
  DeliveryMethodEnum,
  deliveryMethodEnumSchema,
} from './deliveryMethodEnum';
import {
  PaylinkActionEnum,
  paylinkActionEnumSchema,
} from './paylinkActionEnum';
import { StatusCode12Enum, statusCode12EnumSchema } from './statusCode12Enum';

export interface List8 {
  /** Location ID */
  locationId?: string | null;
  /** cc_product_transaction_id */
  ccProductTransactionId?: string | null;
  /** Email */
  email?: string | null;
  /** Amount Due */
  amountDue?: number;
  /** Location Api Id */
  locationApiId?: string | null;
  /** Contact Id */
  contactId?: string | null;
  /** Contact Api Id */
  contactApiId?: string | null;
  /** Paylinke Api Id */
  paylinkApiId?: string | null;
  /** Ach Product Transaction Id */
  achProductTransactionId?: string | null;
  /** Expire Date */
  expireDate?: string | null;
  /** Display Product Transaction Receipt Details */
  displayProductTransactionReceiptDetails?: boolean;
  /** Display Billing Fields */
  displayBillingFields?: boolean;
  /**
   * Delivery Method
   * >0 - Do not send
   * >
   * >1 - Email
   * >
   * >2 - SMS
   * >
   * >3 - Both
   * >
   */
  deliveryMethod?: DeliveryMethodEnum | null;
  /** Cell Phone */
  cellPhone?: string | null;
  /** Description */
  description?: string | null;
  /** Store Token */
  storeToken?: boolean;
  /** Store Token Title */
  storeTokenTitle?: string | null;
  /** Paylink Action */
  paylinkAction?: PaylinkActionEnum | null;
  /** Bank Funded Only Override */
  bankFundedOnlyOverride?: boolean;
  /** Used to apply tags to a paylink. */
  tags?: string[] | null;
  /** Redirect URL Delay in seconds */
  redirectUrlDelay?: number | null;
  /** Redirect URL On Approval */
  redirectUrlOnApprove?: string | null;
  /** Redirect URL On Decline */
  redirectUrlOnDecline?: string | null;
  /** Paylink Id */
  id?: string;
  /** (DEPRECATED) Status Id */
  statusId?: boolean;
  /** Status Code */
  statusCode?: StatusCode12Enum | null;
  /** Active */
  active?: boolean;
  /** Created Time Stamp */
  createdTs?: number;
  /** Modified Time Stamp */
  modifiedTs?: number;
  /** User ID Created the register */
  createdUserId?: string | null;
  /** Last User ID that updated the register */
  modifiedUserId?: string | null;
  [key: string]: unknown;
}

export const list8Schema: Schema<List8> = expandoObject({
  locationId: ['location_id', optional(nullable(string()))],
  ccProductTransactionId: [
    'cc_product_transaction_id',
    optional(nullable(string())),
  ],
  email: ['email', optional(nullable(string()))],
  amountDue: ['amount_due', optional(number())],
  locationApiId: ['location_api_id', optional(nullable(string()))],
  contactId: ['contact_id', optional(nullable(string()))],
  contactApiId: ['contact_api_id', optional(nullable(string()))],
  paylinkApiId: ['paylink_api_id', optional(nullable(string()))],
  achProductTransactionId: [
    'ach_product_transaction_id',
    optional(nullable(string())),
  ],
  expireDate: ['expire_date', optional(nullable(string()))],
  displayProductTransactionReceiptDetails: [
    'display_product_transaction_receipt_details',
    optional(boolean()),
  ],
  displayBillingFields: ['display_billing_fields', optional(boolean())],
  deliveryMethod: [
    'delivery_method',
    optional(nullable(deliveryMethodEnumSchema)),
  ],
  cellPhone: ['cell_phone', optional(nullable(string()))],
  description: ['description', optional(nullable(string()))],
  storeToken: ['store_token', optional(boolean())],
  storeTokenTitle: ['store_token_title', optional(nullable(string()))],
  paylinkAction: [
    'paylink_action',
    optional(nullable(paylinkActionEnumSchema)),
  ],
  bankFundedOnlyOverride: ['bank_funded_only_override', optional(boolean())],
  tags: ['tags', optional(nullable(array(string())))],
  redirectUrlDelay: ['redirect_url_delay', optional(nullable(number()))],
  redirectUrlOnApprove: [
    'redirect_url_on_approve',
    optional(nullable(string())),
  ],
  redirectUrlOnDecline: [
    'redirect_url_on_decline',
    optional(nullable(string())),
  ],
  id: ['id', optional(string())],
  statusId: ['status_id', optional(boolean())],
  statusCode: ['status_code', optional(nullable(statusCode12EnumSchema))],
  active: ['active', optional(boolean())],
  createdTs: ['created_ts', optional(number())],
  modifiedTs: ['modified_ts', optional(number())],
  createdUserId: ['created_user_id', optional(nullable(string()))],
  modifiedUserId: ['modified_user_id', optional(nullable(string()))],
});
