/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  expandoObject,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';
import { Changelog, changelogSchema } from './changelog';
import { PostbackLog, postbackLogSchema } from './postbackLog';
import {
  ProductTransaction,
  productTransactionSchema,
} from './productTransaction';

export interface List {
  /** Batch ID */
  id?: string;
  /** Created Time Stamp */
  createdTs?: number;
  /** Product Transaction Id */
  productTransactionId?: string | null;
  /** Processing Status Id */
  processingStatusId?: number;
  /** Batch Number */
  batchNum?: number | null;
  /** Is Open */
  isOpen?: number | null;
  /** Settlement File Name */
  settlementFileName?: string | null;
  /** Batch Close Ts */
  batchCloseTs?: number | null;
  /** Batch Close Detail */
  batchCloseDetail?: string | null;
  /** Total Sale Amount */
  totalSaleAmount?: number | null;
  /** Total Sale Count */
  totalSaleCount?: number | null;
  /** Total Refund Amount */
  totalRefundAmount?: number | null;
  /** Total Refund Count */
  totalRefundCount?: number | null;
  /** Total Void Amount */
  totalVoidAmount?: number | null;
  /** Total Void Count */
  totalVoidCount?: number | null;
  /** Total Blind Refund Amount */
  totalBlindRefundAmount?: number | null;
  /** Total Blind Refund Count */
  totalBlindRefundCount?: number | null;
  /** Changelog Information on `expand` */
  changelogs?: Changelog[];
  /** Postback Log Information on `expand` */
  postbackLogs?: PostbackLog[];
  /** Product Transaction Information on `expand` */
  productTransaction?: ProductTransaction;
  [key: string]: unknown;
}

export const listSchema: Schema<List> = expandoObject({
  id: ['id', optional(string())],
  createdTs: ['created_ts', optional(number())],
  productTransactionId: [
    'product_transaction_id',
    optional(nullable(string())),
  ],
  processingStatusId: ['processing_status_id', optional(number())],
  batchNum: ['batch_num', optional(nullable(number()))],
  isOpen: ['is_open', optional(nullable(number()))],
  settlementFileName: ['settlement_file_name', optional(nullable(string()))],
  batchCloseTs: ['batch_close_ts', optional(nullable(number()))],
  batchCloseDetail: ['batch_close_detail', optional(nullable(string()))],
  totalSaleAmount: ['total_sale_amount', optional(nullable(number()))],
  totalSaleCount: ['total_sale_count', optional(nullable(number()))],
  totalRefundAmount: ['total_refund_amount', optional(nullable(number()))],
  totalRefundCount: ['total_refund_count', optional(nullable(number()))],
  totalVoidAmount: ['total_void_amount', optional(nullable(number()))],
  totalVoidCount: ['total_void_count', optional(nullable(number()))],
  totalBlindRefundAmount: [
    'total_blind_refund_amount',
    optional(nullable(number())),
  ],
  totalBlindRefundCount: [
    'total_blind_refund_count',
    optional(nullable(number())),
  ],
  changelogs: ['changelogs', optional(array(lazy(() => changelogSchema)))],
  postbackLogs: [
    'postback_logs',
    optional(array(lazy(() => postbackLogSchema))),
  ],
  productTransaction: [
    'product_transaction',
    optional(lazy(() => productTransactionSchema)),
  ],
});
