/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

export interface LocationUser {
  /** Location ID */
  locationId?: string;
  /** User ID */
  userId?: string;
  locationApiId?: string | null;
  id?: string;
  /** Created Time Stamp */
  createdTs?: number;
  /** Modified Time Stamp */
  modifiedTs?: number;
  /** User ID Created the register */
  createdUserId?: string;
  /** Last User ID that updated the register */
  modifiedUserId?: string;
  [key: string]: unknown;
}

export const locationUserSchema: Schema<LocationUser> = expandoObject({
  locationId: ['location_id', optional(string())],
  userId: ['user_id', optional(string())],
  locationApiId: ['location_api_id', optional(nullable(string()))],
  id: ['id', optional(string())],
  createdTs: ['created_ts', optional(number())],
  modifiedTs: ['modified_ts', optional(number())],
  createdUserId: ['created_user_id', optional(string())],
  modifiedUserId: ['modified_user_id', optional(string())],
});
