/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

export interface Locationmarketplace {
  /** Location ID */
  locationId?: string;
  /** Marketplacec ID */
  marketplaceId?: string;
  /** Location API ID */
  locationApiId?: string | null;
  /** User ID */
  userId?: string | null;
  /** Location Marketplace ID */
  id?: string;
  /** Created Time Stamp */
  createdTs?: number | null;
  /** User ID Created the register */
  createdUserId?: string | null;
  [key: string]: unknown;
}

export const locationmarketplaceSchema: Schema<Locationmarketplace> = expandoObject(
  {
    locationId: ['location_id', optional(string())],
    marketplaceId: ['marketplace_id', optional(string())],
    locationApiId: ['location_api_id', optional(nullable(string()))],
    userId: ['user_id', optional(nullable(string()))],
    id: ['id', optional(string())],
    createdTs: ['created_ts', optional(nullable(number()))],
    createdUserId: ['created_user_id', optional(nullable(string()))],
  }
);
