/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema, string } from '../schema';

export interface MerchantList {
  /** Name of the listed merchant as used in the authorization message as defined in ISO 8583. */
  merchantNameListed: string;
  /**
   * Acquirer-assigned Merchant Listed Identifier.
   * This may be the same value that is used in authorisation requests sent on behalf of the 3DS Requestor and is represented in ISO 8583 formatting requirements.
   */
  acquirerMerchantIdListed?: string;
  /**
   * Purchase amount for the merchant in minor units of currency with all punctuation removed.
   * When used in conjunction with the Purchase Currency Exponent field, proper punctuation can be calculated.
   */
  merchantAmount?: string;
  /** Currency Code in which purchase Merchant Amount is expressed. Must be provided as ISO 4217 three-digit currency code except values 955-964 and 999. */
  merchantCurrency?: string;
  /** Minor units of Merchant Currency as specified in the ISO 4217 currency exponent. */
  merchantExponent?: string;
  [key: string]: unknown;
}

export const merchantListSchema: Schema<MerchantList> = expandoObject({
  merchantNameListed: ['merchant_name_listed', string()],
  acquirerMerchantIdListed: ['acquirer_merchant_id_listed', optional(string())],
  merchantAmount: ['merchant_amount', optional(string())],
  merchantCurrency: ['merchant_currency', optional(string())],
  merchantExponent: ['merchant_exponent', optional(string())],
});
