/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  expandoObject,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface MessageExtension {
  /** A unique identifier for the extension. Payment System Registered Application Provider Identifier (RID) is required as prefix of the ID. The maximum length is 64 characters. */
  id?: string;
  /** The name of the extension data set as defined by the extension owner. Maximum length is 64 characters. */
  name?: string;
  /** A boolean value indicating whether the recipient must understand the contents of the extension to interpret the entire message. */
  criticalityIndicator?: boolean;
  /** The data carried in the extension as. The maximum length is 8059 characters. */
  data?: unknown;
  [key: string]: unknown;
}

export const messageExtensionSchema: Schema<MessageExtension> = expandoObject({
  id: ['id', optional(string())],
  name: ['name', optional(string())],
  criticalityIndicator: ['criticality_indicator', optional(boolean())],
  data: ['data', optional(unknown())],
});
