/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, optional, Schema } from '../schema';
import { Detail, detailSchema } from './detail';

export interface Meta {
  /** Error detail */
  details?: Detail[];
  [key: string]: unknown;
}

export const metaSchema: Schema<Meta> = expandoObject({
  details: ['details', optional(array(lazy(() => detailSchema)))],
});
