/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string } from '../schema';
import { Type29Enum, type29EnumSchema } from './type29Enum';

export interface Method50 {
  /** Payment type. Must be unique. */
  type: Type29Enum;
  /** The Product's method (cc/ach) has to match the type. */
  productTransactionId: string;
  [key: string]: unknown;
}

export const method50Schema: Schema<Method50> = expandoObject({
  type: ['type', type29EnumSchema],
  productTransactionId: ['product_transaction_id', string()],
});
