/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MethodEnum
 */
export enum MethodEnum {
  Xor = 'xor',
}

/**
 * Schema for MethodEnum
 */
export const methodEnumSchema: Schema<MethodEnum> = stringEnum(MethodEnum);
