/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema, string } from '../schema';
import { Type29Enum, type29EnumSchema } from './type29Enum';

export interface Method3 {
  /** Payment type. Must be unique. */
  type?: Type29Enum;
  /** The Product's method (cc/ach) has to match the type. */
  productTransactionId?: string;
  [key: string]: unknown;
}

export const method3Schema: Schema<Method3> = expandoObject({
  type: ['type', optional(type29EnumSchema)],
  productTransactionId: ['product_transaction_id', optional(string())],
});
