/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  expandoObject,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';
import { Address1, address1Schema } from './address1';
import { LocationTypeEnum, locationTypeEnumSchema } from './locationTypeEnum';

/** Parent Information on `expand` */
export interface Parent3 {
  /** Location ID */
  id?: string;
  /** Created Time Stamp */
  createdTs?: number;
  /** Modified Time Stamp */
  modifiedTs?: number;
  /** Account number */
  accountNumber?: string | null;
  /** Address */
  address?: Address1;
  /** GUID for Branding Domain */
  brandingDomainId?: string | null;
  /** If true, will email contact receipt for any transaction */
  contactEmailTrxReceiptDefault?: boolean;
  /** GUID for Location's default ACH Product Transaction */
  defaultAch?: string | null;
  /** GUID for Location's default CC Product Transaction */
  defaultCc?: string | null;
  /** Used as from email address when sending various notifications */
  emailReplyTo?: string | null;
  /** Fax number */
  fax?: string | null;
  /** Location api ID */
  locationApiId?: string | null;
  /** Location api key */
  locationApiKey?: string | null;
  /** Can be used to store custom information for location. */
  locationC1?: string | null;
  /** Can be used to store custom information for location. */
  locationC2?: string | null;
  /** Can be used to store custom information for location. */
  locationC3?: string | null;
  /** Name of the company */
  name?: string;
  /** Office phone number */
  officePhone?: string | null;
  /** Office phone extension number */
  officeExtPhone?: string | null;
  /** Time zone */
  tz?: string | null;
  /** Location GUID of the parent location */
  parentId?: string;
  /** If set to true will show 'Notes' tab on Contact */
  showContactNotes?: boolean;
  /** If set to true will show 'Files' tab on Contact */
  showContactFiles?: boolean;
  /** User ID Created the register */
  createdUserId?: string | null;
  /** Location Type */
  locationType?: LocationTypeEnum | null;
  /** Name of the parent location */
  parentName?: string | null;
  /** Ticket Hash Key */
  ticketHashKey?: string | null;
  [key: string]: unknown;
}

export const parent3Schema: Schema<Parent3> = expandoObject({
  id: ['id', optional(string())],
  createdTs: ['created_ts', optional(number())],
  modifiedTs: ['modified_ts', optional(number())],
  accountNumber: ['account_number', optional(nullable(string()))],
  address: ['address', optional(lazy(() => address1Schema))],
  brandingDomainId: ['branding_domain_id', optional(nullable(string()))],
  contactEmailTrxReceiptDefault: [
    'contact_email_trx_receipt_default',
    optional(boolean()),
  ],
  defaultAch: ['default_ach', optional(nullable(string()))],
  defaultCc: ['default_cc', optional(nullable(string()))],
  emailReplyTo: ['email_reply_to', optional(nullable(string()))],
  fax: ['fax', optional(nullable(string()))],
  locationApiId: ['location_api_id', optional(nullable(string()))],
  locationApiKey: ['location_api_key', optional(nullable(string()))],
  locationC1: ['location_c1', optional(nullable(string()))],
  locationC2: ['location_c2', optional(nullable(string()))],
  locationC3: ['location_c3', optional(nullable(string()))],
  name: ['name', optional(string())],
  officePhone: ['office_phone', optional(nullable(string()))],
  officeExtPhone: ['office_ext_phone', optional(nullable(string()))],
  tz: ['tz', optional(nullable(string()))],
  parentId: ['parent_id', optional(string())],
  showContactNotes: ['show_contact_notes', optional(boolean())],
  showContactFiles: ['show_contact_files', optional(boolean())],
  createdUserId: ['created_user_id', optional(nullable(string()))],
  locationType: ['location_type', optional(nullable(locationTypeEnumSchema))],
  parentName: ['parent_name', optional(nullable(string()))],
  ticketHashKey: ['ticket_hash_key', optional(nullable(string()))],
});
