/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PartnerEnum
 */
export enum PartnerEnum {
  Standalone = 'standalone',
  Verticle = 'verticle',
  Vericle = 'Vericle',
  AirVoice = 'AirVoice',
  Drchrono = 'drchrono',
  Schoolleader = 'schoolleader',
  Frontier = 'Frontier',
  ChiroTouch = 'ChiroTouch',
  Platinum = 'Platinum',
  CentralProcessingService = 'CentralProcessingService',
}

/**
 * Schema for PartnerEnum
 */
export const partnerEnumSchema: Schema<PartnerEnum> = stringEnum(PartnerEnum);
