/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentMethod16Enum
 */
export enum PaymentMethod16Enum {
  Cc = 'cc',
  Ach = 'ach',
}

/**
 * Schema for PaymentMethod16Enum
 */
export const paymentMethod16EnumSchema: Schema<PaymentMethod16Enum> = stringEnum(
  PaymentMethod16Enum
);
