/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentMethod9Enum
 */
export enum PaymentMethod9Enum {
  Cc = 'cc',
  Ach = 'ach',
}

/**
 * Schema for PaymentMethod9Enum
 */
export const paymentMethod9EnumSchema: Schema<PaymentMethod9Enum> = stringEnum(
  PaymentMethod9Enum
);
