/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PreOrderPurchaseIndEnum
 */
export enum PreOrderPurchaseIndEnum {
  Enum01 = '01',
  Enum02 = '02',
}

/**
 * Schema for PreOrderPurchaseIndEnum
 */
export const preOrderPurchaseIndEnumSchema: Schema<PreOrderPurchaseIndEnum> = stringEnum(
  PreOrderPurchaseIndEnum
);
