/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

/** Array of pricing items from template to be changed. */
export interface PricingElement {
  /** Item ID. */
  itemId: number;
  /** Item value. */
  itemValue: number;
  /** Item term. */
  itemTerm: number;
  /** Item desciption. */
  itemDescription?: string | null;
  [key: string]: unknown;
}

export const pricingElementSchema: Schema<PricingElement> = expandoObject({
  itemId: ['item_id', number()],
  itemValue: ['item_value', number()],
  itemTerm: ['item_term', number()],
  itemDescription: ['item_description', optional(nullable(string()))],
});
