/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ProcessorEnum
 */
export enum ProcessorEnum {
  Zgate = 'zgate',
  Zgate2 = 'zgate2',
  Zach = 'zach',
  Ach = 'ach',
  Fortisach = 'fortisach',
  Cash = 'cash',
}

/**
 * Schema for ProcessorEnum
 */
export const processorEnumSchema: Schema<ProcessorEnum> = stringEnum(
  ProcessorEnum
);
