/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

/** Quick Invoice Setting Information on `expand` */
export interface QuickInvoiceSetting {
  /** Location API ID */
  locationApiId?: string | null;
  /** Location ID */
  locationId?: string;
  /** Quick Invoice Template */
  quickInvoiceTemplate?: string;
  /** Default Quick Invoice Allow Partial Pay */
  defaultAllowPartialPay?: boolean;
  /** Default Quick Invoice Notification On Due Date */
  defaultNotificationOnDueDate?: boolean;
  /** Default Quick Invoice Notification Days After Due Date */
  defaultNotificationDaysAfterDueDate?: number;
  /** Default Quick Invoice Notification Days Before Due Date */
  defaultNotificationDaysBeforeDueDate?: number;
  /** Show Custom Fields */
  showCustomFields?: boolean;
  /** Quick Invoice Settings ID */
  id?: string;
  [key: string]: unknown;
}

export const quickInvoiceSettingSchema: Schema<QuickInvoiceSetting> = expandoObject(
  {
    locationApiId: ['location_api_id', optional(nullable(string()))],
    locationId: ['location_id', optional(string())],
    quickInvoiceTemplate: ['quick_invoice_template', optional(string())],
    defaultAllowPartialPay: ['default_allow_partial_pay', optional(boolean())],
    defaultNotificationOnDueDate: [
      'default_notification_on_due_date',
      optional(boolean()),
    ],
    defaultNotificationDaysAfterDueDate: [
      'default_notification_days_after_due_date',
      optional(number()),
    ],
    defaultNotificationDaysBeforeDueDate: [
      'default_notification_days_before_due_date',
      optional(number()),
    ],
    showCustomFields: ['show_custom_fields', optional(boolean())],
    id: ['id', optional(string())],
  }
);
