/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

export interface QuickInvoiceView {
  /** Quick Invoice Views Id */
  id?: string;
  /** Quick Invoice ID */
  quickInvoiceId?: string;
  /** Remote Ip */
  remoteIp?: string | null;
  /** Created Time Stamp */
  createdTs?: number | null;
  [key: string]: unknown;
}

export const quickInvoiceViewSchema: Schema<QuickInvoiceView> = expandoObject({
  id: ['id', optional(string())],
  quickInvoiceId: ['quick_invoice_id', optional(string())],
  remoteIp: ['remote_ip', optional(nullable(string()))],
  createdTs: ['created_ts', optional(nullable(number()))],
});
