/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

/** Reason Code Information on `expand` */
export interface ReasonCode {
  /** ID */
  id?: number | null;
  /** Title */
  title?: string;
  [key: string]: unknown;
}

export const reasonCodeSchema: Schema<ReasonCode> = expandoObject({
  id: ['id', optional(nullable(number()))],
  title: ['title', optional(string())],
});
