/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ReasonModelEnum
 */
export enum ReasonModelEnum {
  Contact = 'Contact',
  Transaction = 'Transaction',
  Recurring = 'Recurring',
  User = 'User',
  ProductTransaction = 'ProductTransaction',
  TransactionBatch = 'TransactionBatch',
  QuickInvoice = 'QuickInvoice',
  DataExport = 'DataExport',
  UserReportSchedule = 'UserReportSchedule',
  UserReport = 'UserReport',
  Paylink = 'Paylink',
}

/**
 * Schema for ReasonModelEnum
 */
export const reasonModelEnumSchema: Schema<ReasonModelEnum> = stringEnum(
  ReasonModelEnum
);
