/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

export interface RecurringSplit {
  /** Contact Id */
  contactId?: string | null;
  /** Amount */
  amount?: string | null;
  /** Recurring ID */
  id?: string;
  /** Created Time Stamp */
  createdTs?: number;
  /** User ID Created the register */
  createdUserId?: string | null;
  [key: string]: unknown;
}

export const recurringSplitSchema: Schema<RecurringSplit> = expandoObject({
  contactId: ['contact_id', optional(nullable(string()))],
  amount: ['amount', optional(nullable(string()))],
  id: ['id', optional(string())],
  createdTs: ['created_ts', optional(number())],
  createdUserId: ['created_user_id', optional(nullable(string()))],
});
