/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RegistrationFieldEnum
 */
export enum RegistrationFieldEnum {
  Id = 'id',
  FirstName = 'first_name',
  LastName = 'last_name',
  AccountNumber = 'account_number',
  Email = 'email',
  CompanyName = 'company_name',
  Address = 'address',
  City = 'city',
  State = 'state',
  Zip = 'zip',
  HomePhone = 'home_phone',
  OfficePhone = 'office_phone',
  OfficeExtPhone = 'office_ext_phone',
  CellPhone = 'cell_phone',
  ContactApiId = 'contact_api_id',
  DateOfBirth = 'date_of_birth',
}

/**
 * Schema for RegistrationFieldEnum
 */
export const registrationFieldEnumSchema: Schema<RegistrationFieldEnum> = stringEnum(
  RegistrationFieldEnum
);
