/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

export interface RejectedTransactionAchRetry {
  /** Rejected Transaction ID. */
  rejectedTransactionId?: string;
  /** Return Fee. */
  returnFee?: number | null;
  /** Transaction ACH Retry ID. */
  id?: string;
  /** Retry Transaction ID. */
  retryTransactionId?: string;
  /** Return Fee Transaction ID. */
  returnFeeTransactionId?: string;
  /** Created Time Stamp */
  createdTs?: number;
  /** User ID Created the register */
  createdUserId?: string;
  [key: string]: unknown;
}

export const rejectedTransactionAchRetrySchema: Schema<RejectedTransactionAchRetry> = expandoObject(
  {
    rejectedTransactionId: ['rejected_transaction_id', optional(string())],
    returnFee: ['return_fee', optional(nullable(number()))],
    id: ['id', optional(string())],
    retryTransactionId: ['retry_transaction_id', optional(string())],
    returnFeeTransactionId: ['return_fee_transaction_id', optional(string())],
    createdTs: ['created_ts', optional(number())],
    createdUserId: ['created_user_id', optional(string())],
  }
);
