/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ResourceEnum
 */
export enum ResourceEnum {
  Recurring = 'Recurring',
  Transaction = 'Transaction',
  AccountVault = 'AccountVault',
  DeviceTerm = 'DeviceTerm',
}

/**
 * Schema for ResourceEnum
 */
export const resourceEnumSchema: Schema<ResourceEnum> = stringEnum(
  ResourceEnum
);
