/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema } from '../schema';
import { Data8, data8Schema } from './data8';
import { Type28Enum, type28EnumSchema } from './type28Enum';

export interface ResponseTransactionIntention {
  /** Resource Type */
  type?: Type28Enum;
  data?: Data8;
  [key: string]: unknown;
}

export const responseTransactionIntentionSchema: Schema<ResponseTransactionIntention> = expandoObject(
  {
    type: ['type', optional(type28EnumSchema)],
    data: ['data', optional(lazy(() => data8Schema))],
  }
);
