/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema } from '../schema';
import { Data17, data17Schema } from './data17';
import { Type54Enum, type54EnumSchema } from './type54Enum';

export interface ResponseQuickInvoice {
  /** Resource Type */
  type?: Type54Enum;
  data?: Data17;
  [key: string]: unknown;
}

export const responseQuickInvoiceSchema: Schema<ResponseQuickInvoice> = expandoObject(
  {
    type: ['type', optional(type54EnumSchema)],
    data: ['data', optional(lazy(() => data17Schema))],
  }
);
