/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema } from '../schema';
import { Data23, data23Schema } from './data23';
import { Type82Enum, type82EnumSchema } from './type82Enum';

export interface ResponseTicket {
  /** Resource Type */
  type?: Type82Enum;
  data?: Data23;
  [key: string]: unknown;
}

export const responseTicketSchema: Schema<ResponseTicket> = expandoObject({
  type: ['type', optional(type82EnumSchema)],
  data: ['data', optional(lazy(() => data23Schema))],
});
