/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, optional, Schema } from '../schema';
import { Links, linksSchema } from './links';
import { List10, list10Schema } from './list10';
import { Pagination, paginationSchema } from './pagination';
import { Sort, sortSchema } from './sort';
import { Type63Enum, type63EnumSchema } from './type63Enum';

export interface ResponseRecurringsCollection {
  /** Resource Type */
  type?: Type63Enum;
  /** Resource Members */
  list?: List10[];
  /** Pagination page links */
  links?: Links;
  /** Pagination info */
  pagination?: Pagination;
  /** Sort information used on the results */
  sort?: Sort;
  [key: string]: unknown;
}

export const responseRecurringsCollectionSchema: Schema<ResponseRecurringsCollection> = expandoObject(
  {
    type: ['type', optional(type63EnumSchema)],
    list: ['list', optional(array(lazy(() => list10Schema)))],
    links: ['links', optional(lazy(() => linksSchema))],
    pagination: ['pagination', optional(lazy(() => paginationSchema))],
    sort: ['sort', optional(lazy(() => sortSchema))],
  }
);
