/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema } from '../schema';
import { Data28, data28Schema } from './data28';
import { Type109Enum, type109EnumSchema } from './type109Enum';

export interface ResponseTransactionLevel3Master {
  /** Resource Type */
  type?: Type109Enum;
  data?: Data28;
  [key: string]: unknown;
}

export const responseTransactionLevel3MasterSchema: Schema<ResponseTransactionLevel3Master> = expandoObject(
  {
    type: ['type', optional(type109EnumSchema)],
    data: ['data', optional(lazy(() => data28Schema))],
  }
);
