/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema } from '../schema';
import { Data24, data24Schema } from './data24';
import { Type87Enum, type87EnumSchema } from './type87Enum';

export interface ResponseToken {
  /** Resource Type */
  type?: Type87Enum;
  data?: Data24;
  [key: string]: unknown;
}

export const responseTokenSchema: Schema<ResponseToken> = expandoObject({
  type: ['type', optional(type87EnumSchema)],
  data: ['data', optional(lazy(() => data24Schema))],
});
