/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, optional, Schema, string } from '../schema';

export interface Response417filterChannels {
  /** Response code */
  statusCode?: number;
  /** Expectation Failed */
  error?: string;
  /** Channel filters are not set for this project */
  message?: string;
  [key: string]: unknown;
}

export const response417filterChannelsSchema: Schema<Response417filterChannels> = expandoObject(
  {
    statusCode: ['statusCode', optional(number())],
    error: ['error', optional(string())],
    message: ['message', optional(string())],
  }
);
