/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, optional, Schema } from '../schema';
import { Links, linksSchema } from './links';
import { List4, list4Schema } from './list4';
import { Pagination, paginationSchema } from './pagination';
import { Sort, sortSchema } from './sort';
import { Type23Enum, type23EnumSchema } from './type23Enum';

export interface ResponseDeviceTermsCollection {
  /** Resource Type */
  type?: Type23Enum;
  /** Resource Members */
  list?: List4[];
  /** Pagination page links */
  links?: Links;
  /** Pagination info */
  pagination?: Pagination;
  /** Sort information used on the results */
  sort?: Sort;
  [key: string]: unknown;
}

export const responseDeviceTermsCollectionSchema: Schema<ResponseDeviceTermsCollection> = expandoObject(
  {
    type: ['type', optional(type23EnumSchema)],
    list: ['list', optional(array(lazy(() => list4Schema)))],
    links: ['links', optional(lazy(() => linksSchema))],
    pagination: ['pagination', optional(lazy(() => paginationSchema))],
    sort: ['sort', optional(lazy(() => sortSchema))],
  }
);
