/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, optional, Schema } from '../schema';
import { Links, linksSchema } from './links';
import { List19, list19Schema } from './list19';
import { Pagination, paginationSchema } from './pagination';
import { Sort, sortSchema } from './sort';
import { Type125Enum, type125EnumSchema } from './type125Enum';

export interface ResponseUsersCollection {
  /** Resource Type */
  type?: Type125Enum;
  /** Resource Members */
  list?: List19[];
  /** Pagination page links */
  links?: Links;
  /** Pagination info */
  pagination?: Pagination;
  /** Sort information used on the results */
  sort?: Sort;
  [key: string]: unknown;
}

export const responseUsersCollectionSchema: Schema<ResponseUsersCollection> = expandoObject(
  {
    type: ['type', optional(type125EnumSchema)],
    list: ['list', optional(array(lazy(() => list19Schema)))],
    links: ['links', optional(lazy(() => linksSchema))],
    pagination: ['pagination', optional(lazy(() => paginationSchema))],
    sort: ['sort', optional(lazy(() => sortSchema))],
  }
);
