/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, optional, Schema } from '../schema';
import { Links, linksSchema } from './links';
import { List1, list1Schema } from './list1';
import { Pagination, paginationSchema } from './pagination';
import { Sort, sortSchema } from './sort';
import { Type11Enum, type11EnumSchema } from './type11Enum';

export interface ResponseContactsCollection {
  /** Resource Type */
  type?: Type11Enum;
  /** Resource Members */
  list?: List1[];
  /** Pagination page links */
  links?: Links;
  /** Pagination info */
  pagination?: Pagination;
  /** Sort information used on the results */
  sort?: Sort;
  [key: string]: unknown;
}

export const responseContactsCollectionSchema: Schema<ResponseContactsCollection> = expandoObject(
  {
    type: ['type', optional(type11EnumSchema)],
    list: ['list', optional(array(lazy(() => list1Schema)))],
    links: ['links', optional(lazy(() => linksSchema))],
    pagination: ['pagination', optional(lazy(() => paginationSchema))],
    sort: ['sort', optional(lazy(() => sortSchema))],
  }
);
