/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, optional, Schema } from '../schema';
import { Links, linksSchema } from './links';
import { List18, list18Schema } from './list18';
import { Pagination, paginationSchema } from './pagination';
import { Sort, sortSchema } from './sort';
import { Type119Enum, type119EnumSchema } from './type119Enum';

export interface ResponseUserVerificationsCollection {
  /** Resource Type */
  type?: Type119Enum;
  /** Resource Members */
  list?: List18[];
  /** Pagination page links */
  links?: Links;
  /** Pagination info */
  pagination?: Pagination;
  /** Sort information used on the results */
  sort?: Sort;
  [key: string]: unknown;
}

export const responseUserVerificationsCollectionSchema: Schema<ResponseUserVerificationsCollection> = expandoObject(
  {
    type: ['type', optional(type119EnumSchema)],
    list: ['list', optional(array(lazy(() => list18Schema)))],
    links: ['links', optional(lazy(() => linksSchema))],
    pagination: ['pagination', optional(lazy(() => paginationSchema))],
    sort: ['sort', optional(lazy(() => sortSchema))],
  }
);
