/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema } from '../schema';
import { Data33, data33Schema } from './data33';
import { Type124Enum, type124EnumSchema } from './type124Enum';

export interface ResponseUser {
  /** Resource Type */
  type?: Type124Enum;
  data?: Data33;
  [key: string]: unknown;
}

export const responseUserSchema: Schema<ResponseUser> = expandoObject({
  type: ['type', optional(type124EnumSchema)],
  data: ['data', optional(lazy(() => data33Schema))],
});
