/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema } from '../schema';
import { Data38, data38Schema } from './data38';
import { Type133Enum, type133EnumSchema } from './type133Enum';

export interface ResponseWebhook {
  /** Resource Type */
  type?: Type133Enum;
  data?: Data38;
  [key: string]: unknown;
}

export const responseWebhookSchema: Schema<ResponseWebhook> = expandoObject({
  type: ['type', optional(type133EnumSchema)],
  data: ['data', optional(lazy(() => data38Schema))],
});
