/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, optional, Schema } from '../schema';
import { Links, linksSchema } from './links';
import { List16, list16Schema } from './list16';
import { Pagination, paginationSchema } from './pagination';
import { Sort, sortSchema } from './sort';
import { Type98Enum, type98EnumSchema } from './type98Enum';

export interface ResponseTransactionAchRetrysCollection {
  /** Resource Type */
  type?: Type98Enum;
  /** Resource Members */
  list?: List16[];
  /** Pagination page links */
  links?: Links;
  /** Pagination info */
  pagination?: Pagination;
  /** Sort information used on the results */
  sort?: Sort;
  [key: string]: unknown;
}

export const responseTransactionAchRetrysCollectionSchema: Schema<ResponseTransactionAchRetrysCollection> = expandoObject(
  {
    type: ['type', optional(type98EnumSchema)],
    list: ['list', optional(array(lazy(() => list16Schema)))],
    links: ['links', optional(lazy(() => linksSchema))],
    pagination: ['pagination', optional(lazy(() => paginationSchema))],
    sort: ['sort', optional(lazy(() => sortSchema))],
  }
);
