/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, optional, Schema } from '../schema';
import { Links, linksSchema } from './links';
import { List8, list8Schema } from './list8';
import { Pagination, paginationSchema } from './pagination';
import { Sort, sortSchema } from './sort';
import { Type49Enum, type49EnumSchema } from './type49Enum';

export interface ResponsePaylinksCollection {
  /** Resource Type */
  type?: Type49Enum;
  /** Resource Members */
  list?: List8[];
  /** Pagination page links */
  links?: Links;
  /** Pagination info */
  pagination?: Pagination;
  /** Sort information used on the results */
  sort?: Sort;
  [key: string]: unknown;
}

export const responsePaylinksCollectionSchema: Schema<ResponsePaylinksCollection> = expandoObject(
  {
    type: ['type', optional(type49EnumSchema)],
    list: ['list', optional(array(lazy(() => list8Schema)))],
    links: ['links', optional(lazy(() => linksSchema))],
    pagination: ['pagination', optional(lazy(() => paginationSchema))],
    sort: ['sort', optional(lazy(() => sortSchema))],
  }
);
