/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, optional, Schema } from '../schema';
import { Links, linksSchema } from './links';
import { List9, list9Schema } from './list9';
import { Pagination, paginationSchema } from './pagination';
import { Sort, sortSchema } from './sort';
import { Type57Enum, type57EnumSchema } from './type57Enum';

export interface ResponseQuickInvoicesCollection {
  /** Resource Type */
  type?: Type57Enum;
  /** Resource Members */
  list?: List9[];
  /** Pagination page links */
  links?: Links;
  /** Pagination info */
  pagination?: Pagination;
  /** Sort information used on the results */
  sort?: Sort;
  [key: string]: unknown;
}

export const responseQuickInvoicesCollectionSchema: Schema<ResponseQuickInvoicesCollection> = expandoObject(
  {
    type: ['type', optional(type57EnumSchema)],
    list: ['list', optional(array(lazy(() => list9Schema)))],
    links: ['links', optional(lazy(() => linksSchema))],
    pagination: ['pagination', optional(lazy(() => paginationSchema))],
    sort: ['sort', optional(lazy(() => sortSchema))],
  }
);
