/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema } from '../schema';
import { Data12, data12Schema } from './data12';
import { Type45Enum, type45EnumSchema } from './type45Enum';

export interface ResponseThreeDSAuthentication {
  /** Resource Type */
  type?: Type45Enum;
  data?: Data12;
  [key: string]: unknown;
}

export const responseThreeDSAuthenticationSchema: Schema<ResponseThreeDSAuthentication> = expandoObject(
  {
    type: ['type', optional(type45EnumSchema)],
    data: ['data', optional(lazy(() => data12Schema))],
  }
);
