/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema } from '../schema';
import { Data31, data31Schema } from './data31';
import { Type118Enum, type118EnumSchema } from './type118Enum';

export interface ResponseUserVerification {
  /** Resource Type */
  type?: Type118Enum;
  data?: Data31;
  [key: string]: unknown;
}

export const responseUserVerificationSchema: Schema<ResponseUserVerification> = expandoObject(
  {
    type: ['type', optional(type118EnumSchema)],
    data: ['data', optional(lazy(() => data31Schema))],
  }
);
