/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema } from '../schema';
import { Data15, data15Schema } from './data15';
import { Type48Enum, type48EnumSchema } from './type48Enum';

export interface ResponsePaylink {
  /** Resource Type */
  type?: Type48Enum;
  data?: Data15;
  [key: string]: unknown;
}

export const responsePaylinkSchema: Schema<ResponsePaylink> = expandoObject({
  type: ['type', optional(type48EnumSchema)],
  data: ['data', optional(lazy(() => data15Schema))],
});
