/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SchemeIdEnum
 */
export enum SchemeIdEnum {
  Visa = 'Visa',
  Mastercard = 'Mastercard',
  EnumAmericanExpress = 'American Express',
  Diners = 'Diners',
}

/**
 * Schema for SchemeIdEnum
 */
export const schemeIdEnumSchema: Schema<SchemeIdEnum> = stringEnum(
  SchemeIdEnum
);
