/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SecCodeEnum
 */
export enum SecCodeEnum {
  CCD = 'CCD',
  PPD = 'PPD',
  WEB = 'WEB',
  TEL = 'TEL',
}

/**
 * Schema for SecCodeEnum
 */
export const secCodeEnumSchema: Schema<SecCodeEnum> = stringEnum(SecCodeEnum);
