/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, expandoObject, number, optional, Schema } from '../schema';

export interface Settings {
  /** Enabled */
  enabled?: boolean;
  /** Columns */
  columns?: number;
  /** Rows */
  rows?: number;
  [key: string]: unknown;
}

export const settingsSchema: Schema<Settings> = expandoObject({
  enabled: ['enabled', optional(boolean())],
  columns: ['columns', optional(number())],
  rows: ['rows', optional(number())],
});
