/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, optional, Schema } from '../schema';
import { Field, fieldSchema } from './field';
import { Type4Enum, type4EnumSchema } from './type4Enum';

/** Sort information used on the results */
export interface Sort {
  /** Object type */
  type?: Type4Enum;
  /** [object Object] */
  fields?: Field[];
  [key: string]: unknown;
}

export const sortSchema: Schema<Sort> = expandoObject({
  type: ['type', optional(type4EnumSchema)],
  fields: ['fields', optional(array(lazy(() => fieldSchema)))],
});
