/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SuspiciousAccActivityEnum
 */
export enum SuspiciousAccActivityEnum {
  Enum01 = '01',
  Enum02 = '02',
}

/**
 * Schema for SuspiciousAccActivityEnum
 */
export const suspiciousAccActivityEnumSchema: Schema<SuspiciousAccActivityEnum> = stringEnum(
  SuspiciousAccActivityEnum
);
