/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

export interface TagTransaction {
  /** ID */
  id?: string;
  /** Tag */
  tagId?: string;
  /** Transaction ID */
  transactionId?: string;
  /** Payment Method */
  paymentMethod?: string | null;
  /** Created */
  created?: string | null;
  /** Modified */
  modified?: string | null;
  /** Created Time Stamp */
  createdTs?: number | null;
  /** Modified Time Stamp */
  modifiedTs?: number | null;
  /** User ID Created the register */
  createdUserId?: string | null;
  /** Last User ID that updated the register */
  modifiedUserId?: string | null;
  [key: string]: unknown;
}

export const tagTransactionSchema: Schema<TagTransaction> = expandoObject({
  id: ['id', optional(string())],
  tagId: ['tag_id', optional(string())],
  transactionId: ['transaction_id', optional(string())],
  paymentMethod: ['payment_method', optional(nullable(string()))],
  created: ['created', optional(nullable(string()))],
  modified: ['modified', optional(nullable(string()))],
  createdTs: ['created_ts', optional(nullable(number()))],
  modifiedTs: ['modified_ts', optional(nullable(number()))],
  createdUserId: ['created_user_id', optional(nullable(string()))],
  modifiedUserId: ['modified_user_id', optional(nullable(string()))],
});
