/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

/** Terminal Cvm Information on `expand` */
export interface TerminalCvm {
  /** Terminal Manufacturer Code */
  terminalManufacturerCode?: number;
  /** Title */
  title?: string;
  /** Contact Data */
  contactData?: string | null;
  /** Contactless Data */
  contactlessData?: string | null;
  /** Terminal Manufacturer Cvms Id */
  id?: string;
  /** Created Time Stamp */
  createdTs?: number;
  /** Modified Time Stamp */
  modifiedTs?: number;
  /** User ID Created the register */
  createdUserId?: string;
  /** Last User ID that updated the register */
  modifiedUserId?: string;
  [key: string]: unknown;
}

export const terminalCvmSchema: Schema<TerminalCvm> = expandoObject({
  terminalManufacturerCode: ['terminal_manufacturer_code', optional(number())],
  title: ['title', optional(string())],
  contactData: ['contact_data', optional(nullable(string()))],
  contactlessData: ['contactless_data', optional(nullable(string()))],
  id: ['id', optional(string())],
  createdTs: ['created_ts', optional(number())],
  modifiedTs: ['modified_ts', optional(number())],
  createdUserId: ['created_user_id', optional(string())],
  modifiedUserId: ['modified_user_id', optional(string())],
});
