/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  expandoObject,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';
import {
  CommunicationTypeEnum,
  communicationTypeEnumSchema,
} from './communicationTypeEnum';
import {
  TerminalManufacturerCodeEnum,
  terminalManufacturerCodeEnumSchema,
} from './terminalManufacturerCodeEnum';
import { TerminalTimeouts, terminalTimeoutsSchema } from './terminalTimeouts';
import { TipPercents, tipPercentsSchema } from './tipPercents';

/** Terminal Information on `expand` */
export interface Terminal {
  /** Location ID */
  locationId?: string;
  /** Product Transaction ID */
  defaultProductTransactionId?: string | null;
  /** Terminal Application ID */
  terminalApplicationId?: string;
  /** Terminal CVM ID */
  terminalCvmId?: string | null;
  /**
   * Terminal Manufacturer Code
   * >
   * >
   */
  terminalManufacturerCode?: TerminalManufacturerCodeEnum;
  /** Terminal Name */
  title?: string;
  /** Terminal MAC Address */
  macAddress?: string | null;
  /** Terminal Local IP Address */
  localIpAddress?: string;
  /** Terminal Port */
  port?: number;
  /** Terminal Serial Number */
  serialNumber?: string;
  /** Terminal Number */
  terminalNumber?: string;
  /**
   * The following options outlines some configurable timeout values that can be used to customize the experience at the terminal for the cardholder.
   * >These timeouts are specific to Ingenico devices only.
   * >
   * >These timeouts are specific to Ingenico devices only.
   * >
   */
  terminalTimeouts?: TerminalTimeouts;
  /** A JSON of tip percents the JSON MUST contain only these three fields: percent_1, percent_2, percent_3 */
  tipPercents?: TipPercents;
  /** Location Api ID */
  locationApiId?: string | null;
  /** Terminal Api ID */
  terminalApiId?: string | null;
  /** Header Line 1 */
  headerLine1?: string | null;
  /** Header Line 2 */
  headerLine2?: string | null;
  /** Header Line 3 */
  headerLine3?: string | null;
  /** Header Line 4 */
  headerLine4?: string | null;
  /** Header Line 5 */
  headerLine5?: string | null;
  /** Trailer Line 1 */
  trailerLine1?: string | null;
  /** Trailer Line 2 */
  trailerLine2?: string | null;
  /** Trailer Line 3 */
  trailerLine3?: string | null;
  /** Trailer Line 4 */
  trailerLine4?: string | null;
  /** Trailer Line 5 */
  trailerLine5?: string | null;
  /** Default Checkin */
  defaultCheckin?: string | null;
  /** Default Checkout */
  defaultCheckout?: string | null;
  /** Default Room Rate */
  defaultRoomRate?: number | null;
  /** Default Room Number */
  defaultRoomNumber?: string | null;
  /** Debit */
  debit?: boolean;
  /** EMV */
  emv?: boolean;
  /** Cashback Enable */
  cashbackEnable?: boolean;
  /** Print Enable */
  printEnable?: boolean;
  /** Sig Capture Enable */
  sigCaptureEnable?: boolean;
  /** Is Provisioned */
  isProvisioned?: boolean;
  /** Tip Enable */
  tipEnable?: boolean;
  /** Validated Decryption */
  validatedDecryption?: boolean;
  /** Communication Type */
  communicationType?: CommunicationTypeEnum | null;
  /** Active */
  active?: boolean;
  /** Terminal ID */
  id?: string;
  /** Created Time Stamp */
  createdTs?: number;
  /** Modified Time Stamp */
  modifiedTs?: number;
  /** Modified Time Stamp */
  lastRegistrationTs?: number;
  /** User ID Created the register */
  createdUserId?: string;
  /** Last User ID that updated the register */
  modifiedUserId?: string;
  [key: string]: unknown;
}

export const terminalSchema: Schema<Terminal> = expandoObject({
  locationId: ['location_id', optional(string())],
  defaultProductTransactionId: [
    'default_product_transaction_id',
    optional(nullable(string())),
  ],
  terminalApplicationId: ['terminal_application_id', optional(string())],
  terminalCvmId: ['terminal_cvm_id', optional(nullable(string()))],
  terminalManufacturerCode: [
    'terminal_manufacturer_code',
    optional(terminalManufacturerCodeEnumSchema),
  ],
  title: ['title', optional(string())],
  macAddress: ['mac_address', optional(nullable(string()))],
  localIpAddress: ['local_ip_address', optional(string())],
  port: ['port', optional(number())],
  serialNumber: ['serial_number', optional(string())],
  terminalNumber: ['terminal_number', optional(string())],
  terminalTimeouts: [
    'terminal_timeouts',
    optional(lazy(() => terminalTimeoutsSchema)),
  ],
  tipPercents: ['tip_percents', optional(lazy(() => tipPercentsSchema))],
  locationApiId: ['location_api_id', optional(nullable(string()))],
  terminalApiId: ['terminal_api_id', optional(nullable(string()))],
  headerLine1: ['header_line_1', optional(nullable(string()))],
  headerLine2: ['header_line_2', optional(nullable(string()))],
  headerLine3: ['header_line_3', optional(nullable(string()))],
  headerLine4: ['header_line_4', optional(nullable(string()))],
  headerLine5: ['header_line_5', optional(nullable(string()))],
  trailerLine1: ['trailer_line_1', optional(nullable(string()))],
  trailerLine2: ['trailer_line_2', optional(nullable(string()))],
  trailerLine3: ['trailer_line_3', optional(nullable(string()))],
  trailerLine4: ['trailer_line_4', optional(nullable(string()))],
  trailerLine5: ['trailer_line_5', optional(nullable(string()))],
  defaultCheckin: ['default_checkin', optional(nullable(string()))],
  defaultCheckout: ['default_checkout', optional(nullable(string()))],
  defaultRoomRate: ['default_room_rate', optional(nullable(number()))],
  defaultRoomNumber: ['default_room_number', optional(nullable(string()))],
  debit: ['debit', optional(boolean())],
  emv: ['emv', optional(boolean())],
  cashbackEnable: ['cashback_enable', optional(boolean())],
  printEnable: ['print_enable', optional(boolean())],
  sigCaptureEnable: ['sig_capture_enable', optional(boolean())],
  isProvisioned: ['is_provisioned', optional(boolean())],
  tipEnable: ['tip_enable', optional(boolean())],
  validatedDecryption: ['validated_decryption', optional(boolean())],
  communicationType: [
    'communication_type',
    optional(nullable(communicationTypeEnumSchema)),
  ],
  active: ['active', optional(boolean())],
  id: ['id', optional(string())],
  createdTs: ['created_ts', optional(number())],
  modifiedTs: ['modified_ts', optional(number())],
  lastRegistrationTs: ['last_registration_ts', optional(number())],
  createdUserId: ['created_user_id', optional(string())],
  modifiedUserId: ['modified_user_id', optional(string())],
});
