/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TerminalManufacturerCodeEnum
 */
export enum TerminalManufacturerCodeEnum {
  Enum1 = '1',
  Enum2 = '2',
  Enum4 = '4',
  Enum100 = '100',
}

/**
 * Schema for TerminalManufacturerCodeEnum
 */
export const terminalManufacturerCodeEnumSchema: Schema<TerminalManufacturerCodeEnum> = stringEnum(
  TerminalManufacturerCodeEnum
);
