/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ThreeDsRequestorSpcSupportEnum
 */
export enum ThreeDsRequestorSpcSupportEnum {
  Y = 'Y',
}

/**
 * Schema for ThreeDsRequestorSpcSupportEnum
 */
export const threeDsRequestorSpcSupportEnumSchema: Schema<ThreeDsRequestorSpcSupportEnum> = stringEnum(
  ThreeDsRequestorSpcSupportEnum
);
