/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema, string } from '../schema';
import {
  ThreeDsReqAuthMethodEnum,
  threeDsReqAuthMethodEnumSchema,
} from './threeDsReqAuthMethodEnum';

export interface ThreeDsRequestorAuthenticationInfo {
  /**
   * Mechanism used by the Cardholder to authenticate to the 3DS Requestor. "07" and "08" are accepted as well if 3DS Server initiates authentication with EMV 3DS 2.2.0 version or greater (required protocol version can be set in the preferred_protocol_version field)
   * >01 - No 3DS Requestor authentication occurred (i.e. cardholder "logged in" as guest)
   * >
   * >02 - Login to the cardholder account at the 3DS Requestor system using 3DS Requestor's own credentials
   * >
   * >03 - Login to the cardholder account at the 3DS Requestor system using federated ID
   * >
   * >04 - Login to the cardholder account at the 3DS Requestor system using issuer credentials
   * >
   * >05 - Login to the cardholder account at the 3DS Requestor system using third-party authentication
   * >
   * >06 - Login to the cardholder account at the 3DS Requestor system using FIDO Authenticator
   * >
   * >07 - Login to the cardholder account at the 3DS Requestor system using FIDO Authenticator (FIDO assurance data signed) (EMV 3DS 2.2.0 version or greater)
   * >
   * >08 - SRC Assurance Data (EMV 3DS 2.2.0 version or greater)
   * >
   * >80 through 99 - can be used for PS-specific values, regardless of protocol version
   * >
   */
  threeDsReqAuthMethod?: ThreeDsReqAuthMethodEnum;
  /** Date and time converted into UTC of the cardholder authentication. Field is limited to 12 characters and accepted format is YYYYMMDDHHMM */
  threeDsReqAuthTimestamp?: string;
  /**
   * Stringified array of objects that documents and supports a specific authentication process. In the current version of the specification, this data element is not defined in detail, however the intention is that for each 3DS Requestor Authentication Method, this field carry data that the ACS can use to verify the authentication process. For example, if the 3DS
   * Requestor Authentication Method is:
   * 03 -> then this element can carry information about the provider of the federated ID and related information
   * 06 -> then this element can carry the FIDO attestation data (incl. the signature)
   * 07 -> then this element can carry FIDO Attestation data with the FIDO assurance data signed.
   * 08 -> then this element can carry the SRC assurance data.
   * In versions prior to 2.3.1, this array is limited to a single object.
   * Starting from EMVCo version 2.3.1, the array may have 1-3 elements.
   * This field is optional, but recommended to include.
   */
  threeDsReqAuthData?: string;
  [key: string]: unknown;
}

export const threeDsRequestorAuthenticationInfoSchema: Schema<ThreeDsRequestorAuthenticationInfo> = expandoObject(
  {
    threeDsReqAuthMethod: [
      'three_ds_req_auth_method',
      optional(threeDsReqAuthMethodEnumSchema),
    ],
    threeDsReqAuthTimestamp: [
      'three_ds_req_auth_timestamp',
      optional(string()),
    ],
    threeDsReqAuthData: ['three_ds_req_auth_data', optional(string())],
  }
);
