/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransCharEnum
 */
export enum TransCharEnum {
  Enum01 = '01',
  Enum02 = '02',
}

/**
 * Schema for TransCharEnum
 */
export const transCharEnumSchema: Schema<TransCharEnum> = stringEnum(
  TransCharEnum
);
