/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

export interface TransactionHistory {
  /** Transaction ID */
  transactionId?: string;
  /** Transaction Histories ID */
  id?: string;
  /** Status ID */
  statusId?: number | null;
  /** Event Date TS */
  eventDateTs?: number | null;
  /** Location ID */
  locationId?: string | null;
  /** Created Time Stamp */
  createdTs?: number;
  /** Modified Time Stamp */
  modifiedTs?: number;
  [key: string]: unknown;
}

export const transactionHistorySchema: Schema<TransactionHistory> = expandoObject(
  {
    transactionId: ['transaction_id', optional(string())],
    id: ['id', optional(string())],
    statusId: ['status_id', optional(nullable(number()))],
    eventDateTs: ['event_date_ts', optional(nullable(number()))],
    locationId: ['location_id', optional(nullable(string()))],
    createdTs: ['created_ts', optional(number())],
    modifiedTs: ['modified_ts', optional(number())],
  }
);
