/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema';

/**
 * Enum for TrxSourceCodeEnum
 */
export enum TrxSourceCodeEnum {
  Enum1 = 1,
  Enum2 = 2,
  Enum3 = 3,
  Enum4 = 4,
  Enum5 = 5,
  Enum6 = 6,
  Enum7 = 7,
  Enum8 = 8,
  Enum9 = 9,
  Enum10 = 10,
  Enum11 = 11,
  Enum12 = 12,
  Enum13 = 13,
  Enum14 = 14,
  Enum15 = 15,
  Enum16 = 16,
  Enum17 = 17,
  Enum18 = 18,
}

/**
 * Schema for TrxSourceCodeEnum
 */
export const trxSourceCodeEnumSchema: Schema<TrxSourceCodeEnum> = numberEnum(
  TrxSourceCodeEnum
);
