/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type112Enum
 */
export enum Type112Enum {
  TransactionsCollection = 'TransactionsCollection',
}

/**
 * Schema for Type112Enum
 */
export const type112EnumSchema: Schema<Type112Enum> = stringEnum(Type112Enum);
