/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type67Enum
 */
export enum Type67Enum {
  Signature = 'Signature',
}

/**
 * Schema for Type67Enum
 */
export const type67EnumSchema: Schema<Type67Enum> = stringEnum(Type67Enum);
