/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type73Enum
 */
export enum Type73Enum {
  TagsCollection = 'TagsCollection',
}

/**
 * Schema for Type73Enum
 */
export const type73EnumSchema: Schema<Type73Enum> = stringEnum(Type73Enum);
