/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type72Enum
 */
export enum Type72Enum {
  Tag = 'Tag',
}

/**
 * Schema for Type72Enum
 */
export const type72EnumSchema: Schema<Type72Enum> = stringEnum(Type72Enum);
