/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type129Enum
 */
export enum Type129Enum {
  RemoveVerification = 'RemoveVerification',
}

/**
 * Schema for Type129Enum
 */
export const type129EnumSchema: Schema<Type129Enum> = stringEnum(Type129Enum);
