/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type39Enum
 */
export enum Type39Enum {
  LocationInfosCollection = 'LocationInfosCollection',
}

/**
 * Schema for Type39Enum
 */
export const type39EnumSchema: Schema<Type39Enum> = stringEnum(Type39Enum);
