/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type119Enum
 */
export enum Type119Enum {
  UserVerificationsCollection = 'UserVerificationsCollection',
}

/**
 * Schema for Type119Enum
 */
export const type119EnumSchema: Schema<Type119Enum> = stringEnum(Type119Enum);
