/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type87Enum
 */
export enum Type87Enum {
  Token = 'Token',
}

/**
 * Schema for Type87Enum
 */
export const type87EnumSchema: Schema<Type87Enum> = stringEnum(Type87Enum);
