/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type131Enum
 */
export enum Type131Enum {
  ApplePayValidateMerchant = 'ApplePayValidateMerchant',
}

/**
 * Schema for Type131Enum
 */
export const type131EnumSchema: Schema<Type131Enum> = stringEnum(Type131Enum);
