/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type31Enum
 */
export enum Type31Enum {
  LocationSearchsCollection = 'LocationSearchsCollection',
}

/**
 * Schema for Type31Enum
 */
export const type31EnumSchema: Schema<Type31Enum> = stringEnum(Type31Enum);
