/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type49Enum
 */
export enum Type49Enum {
  PaylinksCollection = 'PaylinksCollection',
}

/**
 * Schema for Type49Enum
 */
export const type49EnumSchema: Schema<Type49Enum> = stringEnum(Type49Enum);
