/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type46Enum
 */
export enum Type46Enum {
  ThreeDSTransaction = 'ThreeDSTransaction',
}

/**
 * Schema for Type46Enum
 */
export const type46EnumSchema: Schema<Type46Enum> = stringEnum(Type46Enum);
