/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type133Enum
 */
export enum Type133Enum {
  Webhook = 'Webhook',
}

/**
 * Schema for Type133Enum
 */
export const type133EnumSchema: Schema<Type133Enum> = stringEnum(Type133Enum);
