/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type23Enum
 */
export enum Type23Enum {
  DeviceTermsCollection = 'DeviceTermsCollection',
}

/**
 * Schema for Type23Enum
 */
export const type23EnumSchema: Schema<Type23Enum> = stringEnum(Type23Enum);
