/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type22Enum
 */
export enum Type22Enum {
  DeviceTerm = 'DeviceTerm',
}

/**
 * Schema for Type22Enum
 */
export const type22EnumSchema: Schema<Type22Enum> = stringEnum(Type22Enum);
