/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type130Enum
 */
export enum Type130Enum {
  SendVerification = 'SendVerification',
}

/**
 * Schema for Type130Enum
 */
export const type130EnumSchema: Schema<Type130Enum> = stringEnum(Type130Enum);
