/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type110Enum
 */
export enum Type110Enum {
  TransactionLevel3Visa = 'TransactionLevel3Visa',
}

/**
 * Schema for Type110Enum
 */
export const type110EnumSchema: Schema<Type110Enum> = stringEnum(Type110Enum);
