/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type108Enum
 */
export enum Type108Enum {
  TransactionBinInfo = 'TransactionBinInfo',
}

/**
 * Schema for Type108Enum
 */
export const type108EnumSchema: Schema<Type108Enum> = stringEnum(Type108Enum);
