/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type44Enum
 */
export enum Type44Enum {
  LocationInfo = 'LocationInfo',
}

/**
 * Schema for Type44Enum
 */
export const type44EnumSchema: Schema<Type44Enum> = stringEnum(Type44Enum);
