/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type125Enum
 */
export enum Type125Enum {
  UsersCollection = 'UsersCollection',
}

/**
 * Schema for Type125Enum
 */
export const type125EnumSchema: Schema<Type125Enum> = stringEnum(Type125Enum);
