/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  expandoObject,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';
import { BillingAddress, billingAddressSchema } from './billingAddress';

export interface V1DeclinedRecurringTransactionPaymentsRequest {
  /** Declined Recurring Transaction Id */
  declinedRecurringTransactionId: string;
  /** Account Number */
  accountNumber: string;
  /** Account Holder Name */
  accountHolderName?: string | null;
  /** Exp Date */
  expDate: string;
  /** Transaction Amount */
  transactionAmount: number;
  /** Description */
  description?: string;
  /** Billing Address Object */
  billingAddress?: BillingAddress;
  /** Tags */
  tags?: string[] | null;
  /** Replace AccountVault */
  replaceAccountVault?: boolean;
  /** Specifies to save account to contacts profile if account_number/track_data is present with either contact_id or contact_api_id in params. */
  saveAccount?: boolean;
  /** If saving token while running a transaction, this will be the title of the token. */
  saveAccountTitle?: string | null;
  /** Subtotal Amount */
  subtotalAmount?: number | null;
  /** Surcharge Amount */
  surchargeAmount?: number | null;
  [key: string]: unknown;
}

export const v1DeclinedRecurringTransactionPaymentsRequestSchema: Schema<V1DeclinedRecurringTransactionPaymentsRequest> = expandoObject(
  {
    declinedRecurringTransactionId: [
      'declined_recurring_transaction_id',
      string(),
    ],
    accountNumber: ['account_number', string()],
    accountHolderName: ['account_holder_name', optional(nullable(string()))],
    expDate: ['exp_date', string()],
    transactionAmount: ['transaction_amount', number()],
    description: ['description', optional(string())],
    billingAddress: [
      'billing_address',
      optional(lazy(() => billingAddressSchema)),
    ],
    tags: ['tags', optional(nullable(array(string())))],
    replaceAccountVault: ['replace_account_vault', optional(boolean())],
    saveAccount: ['save_account', optional(boolean())],
    saveAccountTitle: ['save_account_title', optional(nullable(string()))],
    subtotalAmount: ['subtotal_amount', optional(nullable(number()))],
    surchargeAmount: ['surcharge_amount', optional(nullable(number()))],
  }
);
