/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, nullable, optional, Schema, string } from '../schema';

export interface V1ElementsTicketIntentionRequest {
  /** Used to associate the Ticket with a Contact. */
  contactId?: string | null;
  /** Used to associate the Ticket with a Contact. */
  contactApiId?: string | null;
  /** A valid Location Id associated with the Contact for this Ticket */
  locationId: string;
  /** Include a product_transaction_id to respect it's cvv and address field settings when creating a ticket.  These settings are enforced at the ticket creation level only. */
  productTransactionId?: string | null;
  /** A custom text message that displays after the ticket is created. */
  message?: string | null;
  [key: string]: unknown;
}

export const v1ElementsTicketIntentionRequestSchema: Schema<V1ElementsTicketIntentionRequest> = expandoObject(
  {
    contactId: ['contact_id', optional(nullable(string()))],
    contactApiId: ['contact_api_id', optional(nullable(string()))],
    locationId: ['location_id', string()],
    productTransactionId: [
      'product_transaction_id',
      optional(nullable(string())),
    ],
    message: ['message', optional(nullable(string()))],
  }
);
