/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  expandoObject,
  lazy,
  nullable,
  optional,
  Schema,
  string,
} from '../schema';
import { BroadInfo, broadInfoSchema } from './broadInfo';
import {
  BrowserInformation,
  browserInformationSchema,
} from './browserInformation';
import { Cardholder, cardholderSchema } from './cardholder';
import {
  CardholderAccount,
  cardholderAccountSchema,
} from './cardholderAccount';
import {
  ChallengeMessageExtension,
  challengeMessageExtensionSchema,
} from './challengeMessageExtension';
import { Device, deviceSchema } from './device';
import {
  DeviceChannelEnum,
  deviceChannelEnumSchema,
} from './deviceChannelEnum';
import {
  MessageCategoryEnum,
  messageCategoryEnumSchema,
} from './messageCategoryEnum';
import { MessageExtension, messageExtensionSchema } from './messageExtension';
import { MultiTransaction, multiTransactionSchema } from './multiTransaction';
import {
  PreferredProtocolVersionEnum,
  preferredProtocolVersionEnumSchema,
} from './preferredProtocolVersionEnum';
import { Purchase, purchaseSchema } from './purchase';
import { ThreeDsRequestor, threeDsRequestorSchema } from './threeDsRequestor';
import { ThreeRiIndEnum, threeRiIndEnumSchema } from './threeRiIndEnum';

export interface V1MerchantThreedsecureAuthenticationRequest {
  /** Product Transaction ID to associate with this 3DS request */
  productTransactionId: string;
  /**
   * Specifies the preferred version of 3D Secure protocol to be utilized while executing 3D Secure authentication. 3DS Server initiates an authentication request with the preferred version and if this version is not supported by other 3D Secure components, it falls back to the next supported version(s) and continues authentication.
   * If the preferred version is enforced by setting  #enforcePreferredProtocolVersion flag, but this version is not supported by one of the 3D Secure components, 3DS Server does not initiate an authentication and provides corresponding error message to the customer.
   * If no value is provided, EMV 3DS 2.1.0 version will be used by default.
   * >2.1.0 - prefer authentication with 2.1.0 version
   * >
   * >2.2.0 - prefer authentication with 2.2.0 version
   * >
   * >2.3.1 - prefer authentication with 2.3.1 version
   * >
   */
  preferredProtocolVersion?: PreferredProtocolVersionEnum | null;
  /** Boolean flag that enforces preferred 3D Secure protocol version to be used in 3D Secure authentication. The value should be set true to enforce preferred version. If value is false or not provided, 3DS Server can fall back to next supported 3DS protocol version while initiating 3D Secure authentication. */
  enforcePreferredProtocolVersion?: boolean;
  /**
   * Indicates the type of channel interface being used to initiate the transaction.
   * >02 - Browser (BRW)
   * >
   * >03 - 3DS Requestor Initiated (3RI)
   * >
   */
  deviceChannel: DeviceChannelEnum;
  /**
   * Identifies the category of the message for a specific use case.
   * >01 - Payment Authentication (PA)
   * >
   * >02 - Non-Payment Authentication (NPA)
   * >
   * >80 through 99 - PS Specific Values
   * >
   * >80 - MasterCard Identity Check Insights
   * >
   * >85 - MasterCard Identity Check, Production Validation PA
   * >
   * >86 - MasterCard Identity Check, Production Validation NPA
   * >
   */
  messageCategory: MessageCategoryEnum;
  /**
   * Indicates whether the 3DS Method successfully completed. The value is used only when device_channel = 02 (Browser).
   * From protocol version 2.3.1 this field is required.
   * >Y - Successfully completed
   * >
   * >N - Did not successfully complete
   * >
   * >U - Unavailable - 3DS Method URL was not present in the PRes message data for the card range associated with the Cardholder Account Number.
   * >
   */
  threeDsCompInd?: string | null;
  /**
   * Contains the 3DS Server Transaction ID used during the previous execution of the 3DS method. Accepted value length is 36 characters. Accepted value is a Canonical format as defined in IETF RFC 4122. May utilise any of the specified versions if the output meets specified requirements.
   * This field is required if the 3DS Requestor reuses previous 3DS Method execution with device_channel = 02 (BRW). Available in EMV 3DS 2.3.1 and later versions.
   */
  threeDsMethodId?: string | null;
  /** Contains information for the 3DS Requestor. */
  threeDsRequestor: ThreeDsRequestor;
  /**
   * Universally unique transaction identifier assigned by the 3DS Server to identify a single transaction. This value has 36 characters in a format defined in IETF RFC 4122. In case 3DS Method is previously invoked, the threeDSServerTransID should be sent. If not, 3DS Server will generate a new transaction identifier.
   * If threeDSServerTransID is generated in versioning flow same transaction identifier should be used in Authentication flow which combines them as one transaction.
   */
  threeDsServerTransId?: string | null;
  /** Fully qualified URL of 3DS Requestor website or customer care site. */
  threeDsRequestorUrl?: string | null;
  /** Contains information for the Cardholder Account. */
  cardholderAccount: CardholderAccount;
  /** Contains information for the Cardholder. This field is required unless market or regional mandate restricts sending this information. */
  cardholder?: Cardholder;
  /** Contains purchase information */
  purchase?: Purchase;
  /**
   * Until EMV 3DS 2.2.0:
   * Unstructured information sent between the 3DS Server, the DS and the ACS.
   * This field is not required to be filled by the Requestor and the requirements for the presence of this field are DS specific.
   * Starting from EMV 3DS 2.3.1:
   * Structured information sent between the 3DS Server, the DS and the ACS. 2.3.1 structure is defined below. Accepted value length is maximum 4096 characters. This field is optional.
   */
  broadInfo?: BroadInfo;
  /**
   * Data necessary to support requirements not otherwise defined in the 3D Secure message are carried in a Message Extension. This field is limited to 81,920 characters and it is used in the Authentication Request.
   * Requirements of this field are set by each Directory Server.
   */
  messageExtension?: MessageExtension[];
  /**
   * Data necessary to support requirements not otherwise defined in the 3D Secure message are carried in a Message Extension. This field is limited to 81,920 characters and it is used in the generating of the ChallengeRequest, if challenge is needed.
   * Requirements of this field are set by each Directory Server.
   */
  challengeMessageExtension?: ChallengeMessageExtension[];
  /**
   * Contains browser information.
   * This field is required when device_channel=02 (BRW).
   */
  browserInformation?: BrowserInformation;
  /**
   * Indicates the type of 3RI request. This data element provides additional information to the ACS to determine the best approach for handling a 3RI request.
   * Values 06 through 12 are accepted as well if 3DS Server initiates authentication with EMV 3DS 2.2.0 version or greater (required protocol version can be set in the preferred_protocol_version field).
   * Starting from EMV 3DS 2.3.1:
   *  Required if device_channel = 03 and message_category = 01 or 02.
   *  Values 13 and 14 can be used.
   * >01 - Recurring transaction
   * >
   * >02 - Installment transaction
   * >
   * >03 - Add card
   * >
   * >04 - Maintain card information
   * >
   * >05 - Account verification
   * >
   * >06 - Split/delayed shipment (EMV 3DS 2.2.0 version or greater)
   * >
   * >07 - Top-up (EMV 3DS 2.2.0 version or greater)
   * >
   * >08 - Mail order (EMV 3DS 2.2.0 version or greater)
   * >
   * >09 - Telephone order (EMV 3DS 2.2.0 version or greater)
   * >
   * >10 - Whitelist status check (EMV 3DS 2.2.0 version or greater)
   * >
   * >11 - Other payment (EMV 3DS 2.2.0 version or greater)
   * >
   * >12 - Billing agreement (EMV 3DS 2.2.0 version or greater)
   * >
   * >13 - Device Binding status check (EMV 3DS 2.3.1 version or greater)
   * >
   * >14 - Card Security Code status check (EMV 3DS 2.3.1 version or greater)
   * >
   * >80 through 99 - PS-specific values, regardless of protocol version
   * >
   */
  threeRiInd?: ThreeRiIndEnum | null;
  /**
   * Contains device information.
   * Available for supporting EMV 3DS 2.3.1 and later versions.
   */
  device?: Device;
  /**
   * Additional transaction information in case of multiple transactions or merchants.
   * Available for supporting EMV 3DS 2.3.1 and later versions.
   */
  multiTransaction?: MultiTransaction;
  /**
   * Unique and immutable identifier linked to a device that is consistent across 3DS transactions for the specific user device.
   * Available for supporting EMV 3DS 2.3.1 and later versions.
   */
  deviceId?: string | null;
  /**
   * Identifier of the transacting user’s Browser Account ID.
   * Available for supporting EMV 3DS 2.3.1 and later versions.
   */
  userId?: string | null;
  /** The origin of the payee that will be provided in the SPC Transaction Data as a fully qualified URL. */
  payeeOrigin?: string | null;
  [key: string]: unknown;
}

export const v1MerchantThreedsecureAuthenticationRequestSchema: Schema<V1MerchantThreedsecureAuthenticationRequest> = expandoObject(
  {
    productTransactionId: ['product_transaction_id', string()],
    preferredProtocolVersion: [
      'preferred_protocol_version',
      optional(nullable(preferredProtocolVersionEnumSchema)),
    ],
    enforcePreferredProtocolVersion: [
      'enforce_preferred_protocol_version',
      optional(boolean()),
    ],
    deviceChannel: ['device_channel', deviceChannelEnumSchema],
    messageCategory: ['message_category', messageCategoryEnumSchema],
    threeDsCompInd: ['three_ds_comp_ind', optional(nullable(string()))],
    threeDsMethodId: ['three_ds_method_id', optional(nullable(string()))],
    threeDsRequestor: [
      'three_ds_requestor',
      lazy(() => threeDsRequestorSchema),
    ],
    threeDsServerTransId: [
      'three_ds_server_trans_id',
      optional(nullable(string())),
    ],
    threeDsRequestorUrl: [
      'three_ds_requestor_url',
      optional(nullable(string())),
    ],
    cardholderAccount: [
      'cardholder_account',
      lazy(() => cardholderAccountSchema),
    ],
    cardholder: ['cardholder', optional(lazy(() => cardholderSchema))],
    purchase: ['purchase', optional(lazy(() => purchaseSchema))],
    broadInfo: ['broad_info', optional(lazy(() => broadInfoSchema))],
    messageExtension: [
      'message_extension',
      optional(array(lazy(() => messageExtensionSchema))),
    ],
    challengeMessageExtension: [
      'challenge_message_extension',
      optional(array(lazy(() => challengeMessageExtensionSchema))),
    ],
    browserInformation: [
      'browser_information',
      optional(lazy(() => browserInformationSchema)),
    ],
    threeRiInd: ['three_ri_ind', optional(nullable(threeRiIndEnumSchema))],
    device: ['device', optional(lazy(() => deviceSchema))],
    multiTransaction: [
      'multi_transaction',
      optional(lazy(() => multiTransactionSchema)),
    ],
    deviceId: ['device_id', optional(nullable(string()))],
    userId: ['user_id', optional(nullable(string()))],
    payeeOrigin: ['payee_origin', optional(nullable(string()))],
  }
);
