/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, Schema } from '../schema';
import { Level3Data6, level3Data6Schema } from './level3Data6';

export interface V1TransactionsLevel3VisaRequest {
  /** Level 3 data object */
  level3Data: Level3Data6;
  [key: string]: unknown;
}

export const v1TransactionsLevel3VisaRequestSchema: Schema<V1TransactionsLevel3VisaRequest> = expandoObject(
  { level3Data: ['level3_data', lazy(() => level3Data6Schema)] }
);
