/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Values58Enum
 */
export enum Values58Enum {
  AccountNumber = 'account_number',
  ExpDate = 'exp_date',
}

/**
 * Schema for Values58Enum
 */
export const values58EnumSchema: Schema<Values58Enum> = stringEnum(
  Values58Enum
);
